Meteor.startup(function () {

  if (Posts.find({}).count() === 0) {
    Posts.insert({
      title: Fake.sentence(),
      body: Fake.paragraph(),
      published: Fake.fromArray([true, false])
    });
  }

  if (hymnCollection.find().count() === 0) {
    hymnCollection.insert({number: 1, name: "The Morning Breaks"});
    hymnCollection.insert({number: 2, name: "The Spirit of God"});
    hymnCollection.insert({number: 3, name: "Now Let Us Rejoice"});
    hymnCollection.insert({number: 4, name: "Truth Eternal"});
    hymnCollection.insert({number: 5, name: "High on the Mountain Top"});
    hymnCollection.insert({number: 6, name: "Redeemer of Israel"});
    hymnCollection.insert({number: 7, name: "Israel, Israel, God Is Calling"});
    hymnCollection.insert({number: 8, name: "Awake and Arise"});
    hymnCollection.insert({number: 9, name: "Come, Rejoice"});
    hymnCollection.insert({number: 10, name: "Come, Sing to the Lord"});
    hymnCollection.insert({number: 11, name: "What Was Witnessed in the Heavens?"});
    hymnCollection.insert({number: 12, name: "'Twas Witnessed in the Morning Sky"});
    hymnCollection.insert({number: 13, name: "An Angel from on High"});
    hymnCollection.insert({number: 14, name: "Sweet Is the Peace the Gospel Brings"});
    hymnCollection.insert({number: 15, name: "I Saw a Mighty Angel Fly"});
    hymnCollection.insert({number: 16, name: "What Glorious Scenes Mine Eyes Behold"});
    hymnCollection.insert({number: 17, name: "Awake, Ye Saints of God, Awake!"});
    hymnCollection.insert({number: 18, name: "The Voice of God Again Is Heard"});
    hymnCollection.insert({number: 19, name: "We Thank Thee, O God, for a Prophet"});
    hymnCollection.insert({number: 20, name: "God of Power, God of Right"});
    hymnCollection.insert({number: 21, name: "Come, Listen to a Prophet's Voice"});
    hymnCollection.insert({number: 22, name: "We Listen to a Prophet's Voice"});
    hymnCollection.insert({number: 23, name: "We Ever Pray for Thee"});
    hymnCollection.insert({number: 24, name: "God Bless Our Prophet Dear"});
    hymnCollection.insert({number: 25, name: "Now We'll Sing with One Accord"});
    hymnCollection.insert({number: 26, name: "Joseph Smith's First Prayer"});
    hymnCollection.insert({number: 27, name: "Praise to the Man"});
    hymnCollection.insert({number: 28, name: "Saints, Behold How Great Jehovah"});
    hymnCollection.insert({number: 29, name: "A Poor Wayfaring Man of Grief"});
    hymnCollection.insert({number: 30, name: "Come, Come, Ye Saints"});
    hymnCollection.insert({number: 31, name: "O God, Our Help in Ages Past"});
    hymnCollection.insert({number: 32, name: "The Happy Day at Last Has Come"});
    hymnCollection.insert({number: 33, name: "Our Mountain Home So Dear"});
    hymnCollection.insert({number: 34, name: "O Ye Mountains High"});
    hymnCollection.insert({number: 35, name: "For the Strength of the Hills"});
    hymnCollection.insert({number: 36, name: "They, the Builders of the Nation"});
    hymnCollection.insert({number: 37, name: "The Wintry Day, Descending to Its Close"});
    hymnCollection.insert({number: 38, name: "Come, All Ye Saints of Zion"});
    hymnCollection.insert({number: 39, name: "O Saints of Zion"});
    hymnCollection.insert({number: 40, name: "Arise, O Glorious Zion"});
    hymnCollection.insert({number: 41, name: "Let Zion in Her Beauty Rise"});
    hymnCollection.insert({number: 42, name: "Hail to the Brightness of Zion's Glad Morning!"});
    hymnCollection.insert({number: 43, name: "Zion Stands with Hills Surrounded"});
    hymnCollection.insert({number: 44, name: "Beautiful Zion, Built Above"});
    hymnCollection.insert({number: 45, name: "Lead Me into Life Eternal"});
    hymnCollection.insert({number: 46, name: "Glorious Things of Thee Are Spoken"});
    hymnCollection.insert({number: 47, name: "We Will Sing of Zion"});
    hymnCollection.insert({number: 48, name: "Glorious Things Are Sung of Zion"});
    hymnCollection.insert({number: 49, name: "Adam-ondi Ahman"});
    hymnCollection.insert({number: 50, name: "Come, Thou Glorious Day of Promise"});
    hymnCollection.insert({number: 51, name: "Sons of Michael, He Approaches"});
    hymnCollection.insert({number: 52, name: "The Day Dawn Is Breaking"});
    hymnCollection.insert({number: 53, name: "Let Earth's Inhabitants Rejoice"});
    hymnCollection.insert({number: 54, name: "Behold, the Mountain of the Lord"});
    hymnCollection.insert({number: 55, name: "Lo, the Mighty God Appearing!"});
    hymnCollection.insert({number: 56, name: "Softly Beams the Sacred Dawning"});
    hymnCollection.insert({number: 57, name: "We're Not Ashamed to Own Our Lord"});
    hymnCollection.insert({number: 58, name: "Come, Ye Children of the Lord"});
    hymnCollection.insert({number: 59, name: "Come, O Thou King of Kings"});
    hymnCollection.insert({number: 60, name: "Battle Hymn of the Republic"});
    hymnCollection.insert({number: 61, name: "Raise Your Voices to the Lord"});
    hymnCollection.insert({number: 62, name: "All Creatures of Our God and King"});
    hymnCollection.insert({number: 63, name: "Great King of Heaven"});
    hymnCollection.insert({number: 64, name: "On This Day of Joy and Gladness"});
    hymnCollection.insert({number: 65, name: "Come, All Ye Saints Who Dwell on Earth"});
    hymnCollection.insert({number: 66, name: "Rejoice, the Lord Is King!"});
    hymnCollection.insert({number: 67, name: "Glory to God on High"});
    hymnCollection.insert({number: 68, name: "A Mighty Fortress Is Our God"});
    hymnCollection.insert({number: 69, name: "All Glory, Laud, and Honor"});
    hymnCollection.insert({number: 70, name: "Sing Praise to Him"});
    hymnCollection.insert({number: 71, name: "With Songs of Praise"});
    hymnCollection.insert({number: 72, name: "Praise to the Lord, the Almighty"});
    hymnCollection.insert({number: 73, name: "Praise the Lord with Heart and Voice"});
    hymnCollection.insert({number: 74, name: "Praise Ye the Lord"});
    hymnCollection.insert({number: 75, name: "In hymnCollection of Praise"});
    hymnCollection.insert({number: 76, name: "God of Our Fathers, We Come unto Thee"});
    hymnCollection.insert({number: 77, name: "Great Is the Lord"});
    hymnCollection.insert({number: 78, name: "God of Our Fathers, Whose Almighty Hand"});
    hymnCollection.insert({number: 79, name: "With All the Power of Heart and Tongue"});
    hymnCollection.insert({number: 80, name: "God of Our Fathers, Known of Old"});
    hymnCollection.insert({number: 81, name: "Press Forward, Saints"});
    hymnCollection.insert({number: 82, name: "For All the Saints"});
    hymnCollection.insert({number: 83, name: "Guide Us, O Thou Great Jehovah"});
    hymnCollection.insert({number: 84, name: "Faith of Our Fathers"});
    hymnCollection.insert({number: 85, name: "How Firm a Foundation"});
    hymnCollection.insert({number: 86, name: "How Great Thou Art"});
    hymnCollection.insert({number: 87, name: "God Is Love"});
    hymnCollection.insert({number: 88, name: "Great God, Attend While Zion Sings"});
    hymnCollection.insert({number: 89, name: "The Lord Is My Light"});
    hymnCollection.insert({number: 90, name: "From All That Dwell below the Skies"});
    hymnCollection.insert({number: 91, name: "Father, Thy Children to Thee Now Raise"});
    hymnCollection.insert({number: 92, name: "For the Beauty of the Earth"});
    hymnCollection.insert({number: 93, name: "Prayer of Thanksgiving"});
    hymnCollection.insert({number: 94, name: "Come, Ye Thankful People"});
    hymnCollection.insert({number: 95, name: "Now Thank We All Our God"});
    hymnCollection.insert({number: 96, name: "Dearest Children, God Is Near You"});
    hymnCollection.insert({number: 97, name: "Lead, Kindly Light"});
    hymnCollection.insert({number: 98, name: "I Need Thee Every Hour"});
    hymnCollection.insert({number: 99, name: "Nearer, Dear Savior, to Thee"});
    hymnCollection.insert({number: 100, name: "Nearer, My God, to Thee"});
    hymnCollection.insert({number: 101, name: "Guide Me to Thee"});
    hymnCollection.insert({number: 102, name: "Jesus, Lover of My Soul"});
    hymnCollection.insert({number: 103, name: "Precious Savior, Dear Redeemer"});
    hymnCollection.insert({number: 104, name: "Jesus, Savior, Pilot Me"});
    hymnCollection.insert({number: 105, name: "Master, the Tempest Is Raging"});
    hymnCollection.insert({number: 106, name: "God Speed the Right"});
    hymnCollection.insert({number: 107, name: "Lord, Accept Our True Devotion"});
    hymnCollection.insert({number: 108, name: "The Lord Is My Shepherd"});
    hymnCollection.insert({number: 109, name: "The Lord My Pasture Will Prepare"});
    hymnCollection.insert({number: 110, name: "Cast Thy Burden upon the Lord"});
    hymnCollection.insert({number: 111, name: "Rock of Ages"});
    hymnCollection.insert({number: 112, name: "Savior, Redeemer of My Soul"});
    hymnCollection.insert({number: 113, name: "Our Savior's Love"});
    hymnCollection.insert({number: 114, name: "Come unto Him"});
    hymnCollection.insert({number: 115, name: "Come, Ye Disconsolate"});
    hymnCollection.insert({number: 116, name: "Come, Follow Me"});
    hymnCollection.insert({number: 117, name: "Come unto Jesus"});
    hymnCollection.insert({number: 118, name: "Ye Simple Souls Who Stray"});
    hymnCollection.insert({number: 119, name: "Come, We That Love the Lord"});
    hymnCollection.insert({number: 120, name: "Lean on My Ample Arm"});
    hymnCollection.insert({number: 121, name: "I'm a Pilgrim, I'm a Stranger"});
    hymnCollection.insert({number: 122, name: "Though Deepening Trials"});
    hymnCollection.insert({number: 123, name: "Oh, May My Soul Commune with Thee"});
    hymnCollection.insert({number: 124, name: "Be Still, My Soul"});
    hymnCollection.insert({number: 125, name: "How Gentle God's Commands"});
    hymnCollection.insert({number: 126, name: "How Long, O Lord Most Holy and True"});
    hymnCollection.insert({number: 127, name: "Does the Journey Seem Long?"});
    hymnCollection.insert({number: 128, name: "When Faith Endures"});
    hymnCollection.insert({number: 129, name: "Where Can I Turn for Peace?"});
    hymnCollection.insert({number: 130, name: "Be Thou Humble"});
    hymnCollection.insert({number: 131, name: "More Holiness Give Me"});
    hymnCollection.insert({number: 132, name: "God Is in His Holy Temple"});
    hymnCollection.insert({number: 133, name: "Father in Heaven"});
    hymnCollection.insert({number: 134, name: "I Believe in Christ"});
    hymnCollection.insert({number: 135, name: "My Redeemer Lives"});
    hymnCollection.insert({number: 136, name: "I Know That My Redeemer Lives"});
    hymnCollection.insert({number: 137, name: "Testimony"});
    hymnCollection.insert({number: 138, name: "Bless Our Fast, We Pray"});
    hymnCollection.insert({number: 139, name: "In Fasting We Approach Thee"});
    hymnCollection.insert({number: 140, name: "Did You Think to Pray?"});
    hymnCollection.insert({number: 141, name: "Jesus, the Very Thought of Thee"});
    hymnCollection.insert({number: 142, name: "Sweet Hour of Prayer"});
    hymnCollection.insert({number: 143, name: "Let the Holy Spirit Guide"});
    hymnCollection.insert({number: 144, name: "Secret Prayer"});
    hymnCollection.insert({number: 145, name: "Prayer Is the Soul's Sincere Desire"});
    hymnCollection.insert({number: 146, name: "Gently Raise the Sacred Strain"});
    hymnCollection.insert({number: 147, name: "Sweet Is the Work"});
    hymnCollection.insert({number: 148, name: "Sabbath Day"});
    hymnCollection.insert({number: 149, name: "As the Dew from Heaven Distilling"});
    hymnCollection.insert({number: 150, name: "O Thou Kind and Gracious Father"});
    hymnCollection.insert({number: 151, name: "We Meet, Dear Lord"});
    hymnCollection.insert({number: 152, name: "God Be with You Till We Meet Again"});
    hymnCollection.insert({number: 153, name: "Lord, We Ask Thee Ere We Part"});
    hymnCollection.insert({number: 154, name: "Father, This Hour Has Been One of Joy"});
    hymnCollection.insert({number: 155, name: "We Have Partaken of Thy Love"});
    hymnCollection.insert({number: 156, name: "Sing We Now at Parting"});
    hymnCollection.insert({number: 157, name: "Thy Spirit, Lord, Has Stirred Our Souls"});
    hymnCollection.insert({number: 158, name: "Before Thee, Lord, I Bow My Head"});
    hymnCollection.insert({number: 159, name: "Now the Day Is Over"});
    hymnCollection.insert({number: 160, name: "Softly Now the Light of Day"});
    hymnCollection.insert({number: 161, name: "The Lord Be with Us"});
    hymnCollection.insert({number: 162, name: "Lord, We Come before Thee Now"});
    hymnCollection.insert({number: 163, name: "Lord, Dismiss Us with Thy Blessing"});
    hymnCollection.insert({number: 164, name: "Great God, to Thee My Evening Song"});
    hymnCollection.insert({number: 165, name: "Abide with Me; 'Tis Eventide"});
    hymnCollection.insert({number: 166, name: "Abide with Me!"});
    hymnCollection.insert({number: 167, name: "Come, Let Us Sing an Evening Hymn"});
    hymnCollection.insert({number: 168, name: "As the Shadows Fall"});
    hymnCollection.insert({number: 169, name: "As Now We Take the Sacrament"});
    hymnCollection.insert({number: 170, name: "God, Our Father, Hear Us Pray"});
    hymnCollection.insert({number: 171, name: "With Humble Heart"});
    hymnCollection.insert({number: 172, name: "In Humility, Our Savior"});
    hymnCollection.insert({number: 173, name: "While of These Emblems We Partake"});
    hymnCollection.insert({number: 174, name: "While of These Emblems We Partake"});
    hymnCollection.insert({number: 175, name: "O God, the Eternal Father"});
    hymnCollection.insert({number: 176, name: "'Tis Sweet to Sing the Matchless Love"});
    hymnCollection.insert({number: 177, name: "'Tis Sweet To Sing the Matchless Love"});
    hymnCollection.insert({number: 178, name: "O Lord of Hosts"});
    hymnCollection.insert({number: 179, name: "Again, Our Dear Redeeming Lord"});
    hymnCollection.insert({number: 180, name: "Father in Heaven, We Do Believe"});
    hymnCollection.insert({number: 181, name: "Jesus of Nazareth, Savior and King"});
    hymnCollection.insert({number: 182, name: "We'll Sing All Hail to Jesus' Name"});
    hymnCollection.insert({number: 183, name: "In Remembrance of Thy Suffering"});
    hymnCollection.insert({number: 184, name: "Upon the Cross of Calvary"});
    hymnCollection.insert({number: 185, name: "Reverently and Meekly Now"});
    hymnCollection.insert({number: 186, name: "Again We Meet around the Board"});
    hymnCollection.insert({number: 187, name: "God Loved Us, So He Sent His Son"});
    hymnCollection.insert({number: 188, name: "Thy Will, O Lord, Be Done"});
    hymnCollection.insert({number: 189, name: "O Thou, Before the World Began"});
    hymnCollection.insert({number: 190, name: "In Memory of the Crucified"});
    hymnCollection.insert({number: 191, name: "Behold the Great Redeemer Die"});
    hymnCollection.insert({number: 192, name: "He Died! The Great Redeemer Died"});
    hymnCollection.insert({number: 193, name: "I Stand All Amazed"});
    hymnCollection.insert({number: 194, name: "There Is a Green Hill Far Away"});
    hymnCollection.insert({number: 195, name: "How Great the Wisdom and the Love"});
    hymnCollection.insert({number: 196, name: "Jesus, Once of Humble Birth"});
    hymnCollection.insert({number: 197, name: "O Savior, Thou Who Wearest a Crown"});
    hymnCollection.insert({number: 198, name: "That Easter Morn"});
    hymnCollection.insert({number: 199, name: "He Is Risen!"});
    hymnCollection.insert({number: 200, name: "Christ the Lord Is Risen Today"});
    hymnCollection.insert({number: 201, name: "Joy to the World"});
    hymnCollection.insert({number: 202, name: "Oh, Come, All Ye Faithful"});
    hymnCollection.insert({number: 203, name: "Angels We Have Heard on High"});
    hymnCollection.insert({number: 204, name: "Silent Night"});
    hymnCollection.insert({number: 205, name: "Once in Royal David's City"});
    hymnCollection.insert({number: 206, name: "Away in a Manger"});
    hymnCollection.insert({number: 207, name: "It Came upon the Midnight Clear"});
    hymnCollection.insert({number: 208, name: "O Little Town of Bethlehem"});
    hymnCollection.insert({number: 209, name: "Hark! The Herald Angels Sing"});
    hymnCollection.insert({number: 210, name: "With Wondering Awe"});
    hymnCollection.insert({number: 211, name: "While Shepherds Watched Their Flocks"});
    hymnCollection.insert({number: 212, name: "Far, Far Away on Judea's Plains"});
    hymnCollection.insert({number: 213, name: "The First Noel"});
    hymnCollection.insert({number: 214, name: "I Heard the Bells on Christmas Day"});
    hymnCollection.insert({number: 215, name: "Ring Out, Wild Bells"});
    hymnCollection.insert({number: 216, name: "We Are Sowing"});
    hymnCollection.insert({number: 217, name: "Come, Let Us Anew"});
    hymnCollection.insert({number: 218, name: "We Give Thee But Thine Own"});
    hymnCollection.insert({number: 219, name: "Because I Have Been Given Much"});
    hymnCollection.insert({number: 220, name: "Lord, I Would Follow Thee"});
    hymnCollection.insert({number: 221, name: "Dear to the Heart of the Shepherd"});
    hymnCollection.insert({number: 222, name: "Hear Thou Our Hymn, O Lord"});
    hymnCollection.insert({number: 223, name: "Have I Done Any Good?"});
    hymnCollection.insert({number: 224, name: "I Have Work Enough to Do"});
    hymnCollection.insert({number: 225, name: "We Are Marching On to Glory"});
    hymnCollection.insert({number: 226, name: "Improve the Shining Moments"});
    hymnCollection.insert({number: 227, name: "There Is Sunshine in My Soul Today"});
    hymnCollection.insert({number: 228, name: "You Can Make the Pathway Bright"});
    hymnCollection.insert({number: 229, name: "Today, While the Sun Shines"});
    hymnCollection.insert({number: 230, name: "Scatter Sunshine"});
    hymnCollection.insert({number: 231, name: "Father, Cheer Our Souls Tonight"});
    hymnCollection.insert({number: 232, name: "Let Us Oft Speak Kind Words"});
    hymnCollection.insert({number: 233, name: "Nay, Speak No Ill"});
    hymnCollection.insert({number: 234, name: "Jesus, Mighty King in Zion"});
    hymnCollection.insert({number: 235, name: "Should You Feel Inclined to Censure"});
    hymnCollection.insert({number: 236, name: "Lord, Accept into Thy Kingdom"});
    hymnCollection.insert({number: 237, name: "Do What Is Right"});
    hymnCollection.insert({number: 238, name: "Behold Thy Sons and Daughters, Lord"});
    hymnCollection.insert({number: 239, name: "Choose the Right"});
    hymnCollection.insert({number: 240, name: "Know This, That Every Soul Is Free"});
    hymnCollection.insert({number: 241, name: "Count Your Blessings"});
    hymnCollection.insert({number: 242, name: "Praise God, from Whom All Blessings Flow"});
    hymnCollection.insert({number: 243, name: "Let Us All Press On"});
    hymnCollection.insert({number: 244, name: "Come Along, Come Along"});
    hymnCollection.insert({number: 245, name: "This House We Dedicate to Thee"});
    hymnCollection.insert({number: 246, name: "Onward, Christian Soldiers"});
    hymnCollection.insert({number: 247, name: "We Love Thy House, O God"});
    hymnCollection.insert({number: 248, name: "Up, Awake, Ye Defenders of Zion"});
    hymnCollection.insert({number: 249, name: "Called to Serve"});
    hymnCollection.insert({number: 250, name: "We Are All Enlisted"});
    hymnCollection.insert({number: 251, name: "Behold! A Royal Army"});
    hymnCollection.insert({number: 252, name: "Put Your Shoulder to the Wheel"});
    hymnCollection.insert({number: 253, name: "Like Ten Thousand Legions Marching"});
    hymnCollection.insert({number: 254, name: "True to the Faith"});
    hymnCollection.insert({number: 255, name: "Carry On"});
    hymnCollection.insert({number: 256, name: "As Zion's Youth in Latter Days"});
    hymnCollection.insert({number: 257, name: "Rejoice! A Glorious Sound Is Heard"});
    hymnCollection.insert({number: 258, name: "O Thou Rock of Our Salvation"});
    hymnCollection.insert({number: 259, name: "Hope of Israel"});
    hymnCollection.insert({number: 260, name: "Who's on the Lord's Side?"});
    hymnCollection.insert({number: 261, name: "Thy Servants Are Prepared"});
    hymnCollection.insert({number: 262, name: "Go, Ye Messengers of Glory"});
    hymnCollection.insert({number: 263, name: "Go Forth with Faith"});
    hymnCollection.insert({number: 264, name: "Hark, All Ye Nations!"});
    hymnCollection.insert({number: 265, name: "Arise, O God, and Shine"});
    hymnCollection.insert({number: 266, name: "The Time Is Far Spent"});
    hymnCollection.insert({number: 267, name: "How Wondrous and Great"});
    hymnCollection.insert({number: 268, name: "Come, All Whose Souls Are Lighted"});
    hymnCollection.insert({number: 269, name: "Jehovah, Lord of Heaven and Earth"});
    hymnCollection.insert({number: 270, name: "I'll Go Where You Want Me to Go"});
    hymnCollection.insert({number: 271, name: "Oh, Holy Words of Truth and Love"});
    hymnCollection.insert({number: 272, name: "Oh Say, What Is Truth?"});
    hymnCollection.insert({number: 273, name: "Truth Reflects upon Our Senses"});
    hymnCollection.insert({number: 274, name: "The Iron Rod"});
    hymnCollection.insert({number: 275, name: "Men Are That They Might Have Joy"});
    hymnCollection.insert({number: 276, name: "Come Away to the Sunday School"});
    hymnCollection.insert({number: 277, name: "As I Search the Holy Scriptures"});
    hymnCollection.insert({number: 278, name: "Thanks for the Sabbath School"});
    hymnCollection.insert({number: 279, name: "Thy Holy Word"});
    hymnCollection.insert({number: 280, name: "Welcome, Welcome, Sabbath Morning"});
    hymnCollection.insert({number: 281, name: "Help Me Teach with Inspiration"});
    hymnCollection.insert({number: 282, name: "We Meet Again in Sabbath School"});
    hymnCollection.insert({number: 283, name: "The Glorious Gospel Light Has Shone"});
    hymnCollection.insert({number: 284, name: "If You Could Hie to Kolob"});
    hymnCollection.insert({number: 285, name: "God Moves in a Mysterious Way"});
    hymnCollection.insert({number: 286, name: "Oh, What Songs of the Heart"});
    hymnCollection.insert({number: 287, name: "Rise, Ye Saints, and Temples Enter"});
    hymnCollection.insert({number: 288, name: "How Beautiful Thy Temples, Lord"});
    hymnCollection.insert({number: 289, name: "Holy Temples on Mount Zion"});
    hymnCollection.insert({number: 290, name: "Rejoice, Ye Saints of Latter Days"});
    hymnCollection.insert({number: 291, name: "Turn Your Hearts"});
    hymnCollection.insert({number: 292, name: "O My Father"});
    hymnCollection.insert({number: 293, name: "Each Life That Touches Ours for Good"});
    hymnCollection.insert({number: 294, name: "Love at Home"});
    hymnCollection.insert({number: 295, name: "O Love That Glorifies the Son"});
    hymnCollection.insert({number: 296, name: "Our Father, by Whose Name"});
    hymnCollection.insert({number: 297, name: "From Homes of Saints Glad Songs Arise"});
    hymnCollection.insert({number: 298, name: "Home Can Be a Heaven on Earth"});
    hymnCollection.insert({number: 299, name: "Children of Our Heavenly Father"});
    hymnCollection.insert({number: 300, name: "Families Can Be Together Forever"});
    hymnCollection.insert({number: 301, name: "I Am a Child of God"});
    hymnCollection.insert({number: 302, name: "I Know My Father Lives"});
    hymnCollection.insert({number: 303, name: "Keep the Commandments"});
    hymnCollection.insert({number: 304, name: "Teach Me to Walk in the Light"});
    hymnCollection.insert({number: 305, name: "The Light Divine"});
    hymnCollection.insert({number: 306, name: "God's Daily Care"});
    hymnCollection.insert({number: 307, name: "In Our Lovely Deseret"});
    hymnCollection.insert({number: 308, name: "Love One Another"});
    hymnCollection.insert({number: 309, name: "As Sisters in Zion (Women)"});
    hymnCollection.insert({number: 310, name: "A Key Was Turned in Latter Days (Women)"});
    hymnCollection.insert({number: 311, name: "We Meet Again as Sisters (Women)"});
    hymnCollection.insert({number: 312, name: "We Ever Pray for Thee (Women)"});
    hymnCollection.insert({number: 313, name: "God Is Love (Women)"});
    hymnCollection.insert({number: 314, name: "How Gentle God's Commands (Women)"});
    hymnCollection.insert({number: 315, name: "Jesus, the Very Thought of Thee (Women)"});
    hymnCollection.insert({number: 316, name: "The Lord Is My Shepherd (Women)"});
    hymnCollection.insert({number: 317, name: "Sweet Is the Work (Women)"});
    hymnCollection.insert({number: 318, name: "Love at Home (Women)"});
    hymnCollection.insert({number: 319, name: "Ye Elders of Israel (Men)"});
    hymnCollection.insert({number: 320, name: "The Priesthood of Our Lord (Men)"});
    hymnCollection.insert({number: 321, name: "Ye Who Are Called to Labor (Men)"});
    hymnCollection.insert({number: 322, name: "Come, All Ye Sons of God (Men)"});
    hymnCollection.insert({number: 323, name: "Rise Up, O Men of God (Men's Choir)"});
    hymnCollection.insert({number: 324, name: "Rise Up, O Men of God (Men)"});
    hymnCollection.insert({number: 325, name: "See the Mighty Priesthood Gathered (Men's Choir)"});
    hymnCollection.insert({number: 326, name: "Come, Come, Ye Saints (Men's Choir)"});
    hymnCollection.insert({number: 327, name: "Go, Ye Messengers of Heaven (Men's Choir)"});
    hymnCollection.insert({number: 328, name: "An Angel from on High"});
    hymnCollection.insert({number: 329, name: "Thy Servants Are Prepared (Men's Choir)"});
    hymnCollection.insert({number: 330, name: "See, the Mighty Angel Flying (Men's Choir)"});
    hymnCollection.insert({number: 331, name: "Oh Say, What Is Truth? (Men's Choir)"});
    hymnCollection.insert({number: 332, name: "Come, O Thou King of Kings (Men's Choir)"});
    hymnCollection.insert({number: 333, name: "High on the Mountain Top (Men's Choir)"});
    hymnCollection.insert({number: 334, name: "I Need Thee Every Hour (Men's Choir)"});
    hymnCollection.insert({number: 335, name: "Brightly Beams Our Father's Mercy (Men's Choir)"});
    hymnCollection.insert({number: 336, name: "School Thy Feelings (Men's Choir)"});
    hymnCollection.insert({number: 337, name: "O Home Beloved (Men's Choir)"});
    hymnCollection.insert({number: 338, name: "America the Beautiful"});
    hymnCollection.insert({number: 339, name: "My Country, 'Tis of Thee"});
    hymnCollection.insert({number: 340, name: "The Star Spangled Banner"});
    hymnCollection.insert({number: 341, name: "God Save the King"});
  };

  if (recognitionTypeCollection.find().count() === 0) {
    recognitionTypeCollection.insert({typeName: "Baby Blessing"});
    recognitionTypeCollection.insert({typeName: "Baptism"});
    recognitionTypeCollection.insert({typeName: "Confirmation"});
    recognitionTypeCollection.insert({typeName: "Aaronic Priesthood Advancement"});
    recognitionTypeCollection.insert({typeName: "Primary Advancement"});
    recognitionTypeCollection.insert({typeName: "Mission Call"});
  }

});
