//for monitoring from kadira
//Kadira.connect("pvBC29Y6Tu8fjkn7R", "27e67b07-c1e1-4784-9681-834a00969d3e");

Meteor.startup(function () {

  //add hidden collection to Houson admin console
  Houston.add_collection(Meteor.users);

  memberCollection._ensureIndex({ "individualId": 1});
  memberCollection._ensureIndex({ "wardUnitNo": 1});
  memberCollection._ensureIndex({ "stakeUnitNo": 1});
  memberCollection._ensureIndex({ "callings.positionTypeId": 1});
  memberCollection._ensureIndex({ "callings.orgTypeId": 1});
  memberCollection._ensureIndex({ "switchedPreferredName": 1});
  memberCollection._ensureIndex({ "preferredName": 1});

  callingCollection._ensureIndex({ "wardUnitNo": 1});
  callingCollection._ensureIndex({ "stakeUnitNo": 1});

  callingGroupCollection._ensureIndex({ "wardUnitNo": 1});
  callingGroupCollection._ensureIndex({ "stakeUnitNo": 1});
  
  callingChangeCollection._ensureIndex({ "wardUnitNo": 1});
  callingChangeCollection._ensureIndex({ "stakeUnitNo": 1});
  callingChangeCollection._ensureIndex({ "calling._id": 1});
  callingChangeCollection._ensureIndex({ "calling.displayName": 1});
  callingChangeCollection._ensureIndex({ "calling.positionName": 1});
  callingChangeCollection._ensureIndex({ "calling.wardUnitNo": 1});
  callingChangeCollection._ensureIndex({ "meeting._id": 1});
  callingChangeCollection._ensureIndex({ "meeting.meetingDate": 1});
  callingChangeCollection._ensureIndex({ "member._id": 1});
  callingChangeCollection._ensureIndex({ "member.individualId": 1});
  callingChangeCollection._ensureIndex({ "member.switchedPreferredName": 1});
  callingChangeCollection._ensureIndex({ "type": 1});
  callingChangeCollection._ensureIndex({ "status": 1});

  householdCollection._ensureIndex({ "wardUnitNo": 1});
  householdCollection._ensureIndex({ "stakeUnitNo": 1});
  householdCollection._ensureIndex({ "headOfHouse.individualId": 1});
  householdCollection._ensureIndex({ "spouse.individualId": 1});
  householdCollection._ensureIndex({ "children.individualId": 1});

  meetingCollection._ensureIndex({ "wardUnitNo": 1});
  meetingCollection._ensureIndex({ "stakeUnitNo": 1});
  meetingCollection._ensureIndex({ "meetingDate": 1});

  speakerCollection._ensureIndex({ "wardUnitNo": 1});
  speakerCollection._ensureIndex({ "stakeUnitNo": 1});
  speakerCollection._ensureIndex({ "speaker.individualId": 1});

  recognitionCollection._ensureIndex({ "wardUnitNo": 1});
  recognitionCollection._ensureIndex({ "stakeUnitNo": 1});

  announcementCollection._ensureIndex({ "wardUnitNo": 1});
  announcementCollection._ensureIndex({ "stakeUnitNo": 1});

  musicalNumberCollection._ensureIndex({ "wardUnitNo": 1});
  musicalNumberCollection._ensureIndex({ "stakeUnitNo": 1});

  intermediateHymnCollection._ensureIndex({ "wardUnitNo": 1});
  intermediateHymnCollection._ensureIndex({ "stakeUnitNo": 1});

  signupCollection._ensureIndex({ "wardUnitNo": 1});
  signupCollection._ensureIndex({ "stakeUnitNo": 1});

  volunteerCollection._ensureIndex({ "wardUnitNo": 1});
  volunteerCollection._ensureIndex({ "stakeUnitNo": 1});
  volunteerCollection._ensureIndex({ "volunteer.individualId": 1});

  unitCollection._ensureIndex({ "wardUnitNo": 1});
  unitCollection._ensureIndex({ "stakeUnitNo": 1});

  if (hymnCollection.find().count() == 0) {
    hymnCollection.insert({number: 1, numberText: "1", name: "The Morning Breaks", type: "hymn"});
    hymnCollection.insert({number: 2, numberText: "2", name: "The Spirit of God", type: "hymn"});
    hymnCollection.insert({number: 3, numberText: "3", name: "Now Let Us Rejoice", type: "hymn"});
    hymnCollection.insert({number: 4, numberText: "4", name: "Truth Eternal", type: "hymn"});
    hymnCollection.insert({number: 5, numberText: "5", name: "High on the Mountain Top", type: "hymn"});
    hymnCollection.insert({number: 6, numberText: "6", name: "Redeemer of Israel", type: "hymn"});
    hymnCollection.insert({number: 7, numberText: "7", name: "Israel, Israel, God Is Calling", type: "hymn"});
    hymnCollection.insert({number: 8, numberText: "8", name: "Awake and Arise", type: "hymn"});
    hymnCollection.insert({number: 9, numberText: "9", name: "Come, Rejoice", type: "hymn"});
    hymnCollection.insert({number: 10, numberText: "10", name: "Come, Sing to the Lord", type: "hymn"});
    hymnCollection.insert({number: 11, numberText: "11", name: "What Was Witnessed in the Heavens?", type: "hymn"});
    hymnCollection.insert({number: 12, numberText: "12", name: "Twas Witnessed in the Morning Sky", type: "hymn"});
    hymnCollection.insert({number: 13, numberText: "13", name: "An Angel from on High", type: "hymn"});
    hymnCollection.insert({number: 14, numberText: "14", name: "Sweet Is the Peace the Gospel Brings", type: "hymn"});
    hymnCollection.insert({number: 15, numberText: "15", name: "I Saw a Mighty Angel Fly", type: "hymn"});
    hymnCollection.insert({number: 16, numberText: "16", name: "What Glorious Scenes Mine Eyes Behold", type: "hymn"});
    hymnCollection.insert({number: 17, numberText: "17", name: "Awake, Ye Saints of God, Awake!", type: "hymn"});
    hymnCollection.insert({number: 18, numberText: "18", name: "The Voice of God Again Is Heard", type: "hymn"});
    hymnCollection.insert({number: 19, numberText: "19", name: "We Thank Thee, O God, for a Prophet", type: "hymn"});
    hymnCollection.insert({number: 20, numberText: "20", name: "God of Power, God of Right", type: "hymn"});
    hymnCollection.insert({number: 21, numberText: "21", name: "Come, Listen to a Prophet's Voice", type: "hymn"});
    hymnCollection.insert({number: 22, numberText: "22", name: "We Listen to a Prophet's Voice", type: "hymn"});
    hymnCollection.insert({number: 23, numberText: "23", name: "We Ever Pray for Thee", type: "hymn"});
    hymnCollection.insert({number: 24, numberText: "24", name: "God Bless Our Prophet Dear", type: "hymn"});
    hymnCollection.insert({number: 25, numberText: "25", name: "Now We'll Sing with One Accord", type: "hymn"});
    hymnCollection.insert({number: 26, numberText: "26", name: "Joseph Smith's First Prayer", type: "hymn"});
    hymnCollection.insert({number: 27, numberText: "27", name: "Praise to the Man", type: "hymn"});
    hymnCollection.insert({number: 28, numberText: "28", name: "Saints, Behold How Great Jehovah", type: "hymn"});
    hymnCollection.insert({number: 29, numberText: "29", name: "A Poor Wayfaring Man of Grief", type: "hymn"});
    hymnCollection.insert({number: 30, numberText: "30", name: "Come, Come, Ye Saints", type: "hymn"});
    hymnCollection.insert({number: 31, numberText: "31", name: "O God, Our Help in Ages Past", type: "hymn"});
    hymnCollection.insert({number: 32, numberText: "32", name: "The Happy Day at Last Has Come", type: "hymn"});
    hymnCollection.insert({number: 33, numberText: "33", name: "Our Mountain Home So Dear", type: "hymn"});
    hymnCollection.insert({number: 34, numberText: "34", name: "O Ye Mountains High", type: "hymn"});
    hymnCollection.insert({number: 35, numberText: "35", name: "For the Strength of the Hills", type: "hymn"});
    hymnCollection.insert({number: 36, numberText: "36", name: "They, the Builders of the Nation", type: "hymn"});
    hymnCollection.insert({number: 37, numberText: "37", name: "The Wintry Day, Descending to Its Close", type: "hymn"});
    hymnCollection.insert({number: 38, numberText: "38", name: "Come, All Ye Saints of Zion", type: "hymn"});
    hymnCollection.insert({number: 39, numberText: "39", name: "O Saints of Zion", type: "hymn"});
    hymnCollection.insert({number: 40, numberText: "40", name: "Arise, O Glorious Zion", type: "hymn"});
    hymnCollection.insert({number: 41, numberText: "41", name: "Let Zion in Her Beauty Rise", type: "hymn"});
    hymnCollection.insert({number: 42, numberText: "42", name: "Hail to the Brightness of Zion's Glad Morning!", type: "hymn"});
    hymnCollection.insert({number: 43, numberText: "43", name: "Zion Stands with Hills Surrounded", type: "hymn"});
    hymnCollection.insert({number: 44, numberText: "44", name: "Beautiful Zion, Built Above", type: "hymn"});
    hymnCollection.insert({number: 45, numberText: "45", name: "Lead Me into Life Eternal", type: "hymn"});
    hymnCollection.insert({number: 46, numberText: "46", name: "Glorious Things of Thee Are Spoken", type: "hymn"});
    hymnCollection.insert({number: 47, numberText: "47", name: "We Will Sing of Zion", type: "hymn"});
    hymnCollection.insert({number: 48, numberText: "48", name: "Glorious Things Are Sung of Zion", type: "hymn"});
    hymnCollection.insert({number: 49, numberText: "49", name: "Adam-ondi Ahman", type: "hymn"});
    hymnCollection.insert({number: 50, numberText: "50", name: "Come, Thou Glorious Day of Promise", type: "hymn"});
    hymnCollection.insert({number: 51, numberText: "51", name: "Sons of Michael, He Approaches", type: "hymn"});
    hymnCollection.insert({number: 52, numberText: "52", name: "The Day Dawn Is Breaking", type: "hymn"});
    hymnCollection.insert({number: 53, numberText: "53", name: "Let Earth's Inhabitants Rejoice", type: "hymn"});
    hymnCollection.insert({number: 54, numberText: "54", name: "Behold, the Mountain of the Lord", type: "hymn"});
    hymnCollection.insert({number: 55, numberText: "55", name: "Lo, the Mighty God Appearing!", type: "hymn"});
    hymnCollection.insert({number: 56, numberText: "56", name: "Softly Beams the Sacred Dawning", type: "hymn"});
    hymnCollection.insert({number: 57, numberText: "57", name: "We're Not Ashamed to Own Our Lord", type: "hymn"});
    hymnCollection.insert({number: 58, numberText: "58", name: "Come, Ye Children of the Lord", type: "hymn"});
    hymnCollection.insert({number: 59, numberText: "59", name: "Come, O Thou King of Kings", type: "hymn"});
    hymnCollection.insert({number: 60, numberText: "60", name: "Battle Hymn of the Republic", type: "hymn"});
    hymnCollection.insert({number: 61, numberText: "61", name: "Raise Your Voices to the Lord", type: "hymn"});
    hymnCollection.insert({number: 62, numberText: "62", name: "All Creatures of Our God and King", type: "hymn"});
    hymnCollection.insert({number: 63, numberText: "63", name: "Great King of Heaven", type: "hymn"});
    hymnCollection.insert({number: 64, numberText: "64", name: "On This Day of Joy and Gladness", type: "hymn"});
    hymnCollection.insert({number: 65, numberText: "65", name: "Come, All Ye Saints Who Dwell on Earth", type: "hymn"});
    hymnCollection.insert({number: 66, numberText: "66", name: "Rejoice, the Lord Is King!", type: "hymn"});
    hymnCollection.insert({number: 67, numberText: "67", name: "Glory to God on High", type: "hymn"});
    hymnCollection.insert({number: 68, numberText: "68", name: "A Mighty Fortress Is Our God", type: "hymn"});
    hymnCollection.insert({number: 69, numberText: "69", name: "All Glory, Laud, and Honor", type: "hymn"});
    hymnCollection.insert({number: 70, numberText: "70", name: "Sing Praise to Him", type: "hymn"});
    hymnCollection.insert({number: 71, numberText: "71", name: "With Songs of Praise", type: "hymn"});
    hymnCollection.insert({number: 72, numberText: "72", name: "Praise to the Lord, the Almighty", type: "hymn"});
    hymnCollection.insert({number: 73, numberText: "73", name: "Praise the Lord with Heart and Voice", type: "hymn"});
    hymnCollection.insert({number: 74, numberText: "74", name: "Praise Ye the Lord", type: "hymn"});
    hymnCollection.insert({number: 75, numberText: "75", name: "In hymnCollection of Praise", type: "hymn"});
    hymnCollection.insert({number: 76, numberText: "76", name: "God of Our Fathers, We Come unto Thee", type: "hymn"});
    hymnCollection.insert({number: 77, numberText: "77", name: "Great Is the Lord", type: "hymn"});
    hymnCollection.insert({number: 78, numberText: "78", name: "God of Our Fathers, Whose Almighty Hand", type: "hymn"});
    hymnCollection.insert({number: 79, numberText: "79", name: "With All the Power of Heart and Tongue", type: "hymn"});
    hymnCollection.insert({number: 80, numberText: "80", name: "God of Our Fathers, Known of Old", type: "hymn"});
    hymnCollection.insert({number: 81, numberText: "81", name: "Press Forward, Saints", type: "hymn"});
    hymnCollection.insert({number: 82, numberText: "82", name: "For All the Saints", type: "hymn"});
    hymnCollection.insert({number: 83, numberText: "83", name: "Guide Us, O Thou Great Jehovah", type: "hymn"});
    hymnCollection.insert({number: 84, numberText: "84", name: "Faith of Our Fathers", type: "hymn"});
    hymnCollection.insert({number: 85, numberText: "85", name: "How Firm a Foundation", type: "hymn"});
    hymnCollection.insert({number: 86, numberText: "86", name: "How Great Thou Art", type: "hymn"});
    hymnCollection.insert({number: 87, numberText: "87", name: "God Is Love", type: "hymn"});
    hymnCollection.insert({number: 88, numberText: "88", name: "Great God, Attend While Zion Sings", type: "hymn"});
    hymnCollection.insert({number: 89, numberText: "89", name: "The Lord Is My Light", type: "hymn"});
    hymnCollection.insert({number: 90, numberText: "90", name: "From All That Dwell below the Skies", type: "hymn"});
    hymnCollection.insert({number: 91, numberText: "91", name: "Father, Thy Children to Thee Now Raise", type: "hymn"});
    hymnCollection.insert({number: 92, numberText: "92", name: "For the Beauty of the Earth", type: "hymn"});
    hymnCollection.insert({number: 93, numberText: "93", name: "Prayer of Thanksgiving", type: "hymn"});
    hymnCollection.insert({number: 94, numberText: "94", name: "Come, Ye Thankful People", type: "hymn"});
    hymnCollection.insert({number: 95, numberText: "95", name: "Now Thank We All Our God", type: "hymn"});
    hymnCollection.insert({number: 96, numberText: "96", name: "Dearest Children, God Is Near You", type: "hymn"});
    hymnCollection.insert({number: 97, numberText: "97", name: "Lead, Kindly Light", type: "hymn"});
    hymnCollection.insert({number: 98, numberText: "98", name: "I Need Thee Every Hour", type: "hymn"});
    hymnCollection.insert({number: 99, numberText: "99", name: "Nearer, Dear Savior, to Thee", type: "hymn"});
    hymnCollection.insert({number: 100, numberText: "100", name: "Nearer, My God, to Thee", type: "hymn"});
    hymnCollection.insert({number: 101, numberText: "101", name: "Guide Me to Thee", type: "hymn"});
    hymnCollection.insert({number: 102, numberText: "102", name: "Jesus, Lover of My Soul", type: "hymn"});
    hymnCollection.insert({number: 103, numberText: "103", name: "Precious Savior, Dear Redeemer", type: "hymn"});
    hymnCollection.insert({number: 104, numberText: "104", name: "Jesus, Savior, Pilot Me", type: "hymn"});
    hymnCollection.insert({number: 105, numberText: "105", name: "Master, the Tempest Is Raging", type: "hymn"});
    hymnCollection.insert({number: 106, numberText: "106", name: "God Speed the Right", type: "hymn"});
    hymnCollection.insert({number: 107, numberText: "107", name: "Lord, Accept Our True Devotion", type: "hymn"});
    hymnCollection.insert({number: 108, numberText: "108", name: "The Lord Is My Shepherd", type: "hymn"});
    hymnCollection.insert({number: 109, numberText: "109", name: "The Lord My Pasture Will Prepare", type: "hymn"});
    hymnCollection.insert({number: 110, numberText: "110", name: "Cast Thy Burden upon the Lord", type: "hymn"});
    hymnCollection.insert({number: 111, numberText: "111", name: "Rock of Ages", type: "hymn"});
    hymnCollection.insert({number: 112, numberText: "112", name: "Savior, Redeemer of My Soul", type: "hymn"});
    hymnCollection.insert({number: 113, numberText: "113", name: "Our Savior's Love", type: "hymn"});
    hymnCollection.insert({number: 114, numberText: "114", name: "Come unto Him", type: "hymn"});
    hymnCollection.insert({number: 115, numberText: "115", name: "Come, Ye Disconsolate", type: "hymn"});
    hymnCollection.insert({number: 116, numberText: "116", name: "Come, Follow Me", type: "hymn"});
    hymnCollection.insert({number: 117, numberText: "117", name: "Come unto Jesus", type: "hymn"});
    hymnCollection.insert({number: 118, numberText: "118", name: "Ye Simple Souls Who Stray", type: "hymn"});
    hymnCollection.insert({number: 119, numberText: "119", name: "Come, We That Love the Lord", type: "hymn"});
    hymnCollection.insert({number: 120, numberText: "120", name: "Lean on My Ample Arm", type: "hymn"});
    hymnCollection.insert({number: 121, numberText: "121", name: "I'm a Pilgrim, I'm a Stranger", type: "hymn"});
    hymnCollection.insert({number: 122, numberText: "122", name: "Though Deepening Trials", type: "hymn"});
    hymnCollection.insert({number: 123, numberText: "123", name: "Oh, May My Soul Commune with Thee", type: "hymn"});
    hymnCollection.insert({number: 124, numberText: "124", name: "Be Still, My Soul", type: "hymn"});
    hymnCollection.insert({number: 125, numberText: "125", name: "How Gentle God's Commands", type: "hymn"});
    hymnCollection.insert({number: 126, numberText: "126", name: "How Long, O Lord Most Holy and True", type: "hymn"});
    hymnCollection.insert({number: 127, numberText: "127", name: "Does the Journey Seem Long?", type: "hymn"});
    hymnCollection.insert({number: 128, numberText: "128", name: "When Faith Endures", type: "hymn"});
    hymnCollection.insert({number: 129, numberText: "129", name: "Where Can I Turn for Peace?", type: "hymn"});
    hymnCollection.insert({number: 130, numberText: "130", name: "Be Thou Humble", type: "hymn"});
    hymnCollection.insert({number: 131, numberText: "131", name: "More Holiness Give Me", type: "hymn"});
    hymnCollection.insert({number: 132, numberText: "132", name: "God Is in His Holy Temple", type: "hymn"});
    hymnCollection.insert({number: 133, numberText: "133", name: "Father in Heaven", type: "hymn"});
    hymnCollection.insert({number: 134, numberText: "134", name: "I Believe in Christ", type: "hymn"});
    hymnCollection.insert({number: 135, numberText: "135", name: "My Redeemer Lives", type: "hymn"});
    hymnCollection.insert({number: 136, numberText: "136", name: "I Know That My Redeemer Lives", type: "hymn"});
    hymnCollection.insert({number: 137, numberText: "137", name: "Testimony", type: "hymn"});
    hymnCollection.insert({number: 138, numberText: "138", name: "Bless Our Fast, We Pray", type: "hymn"});
    hymnCollection.insert({number: 139, numberText: "139", name: "In Fasting We Approach Thee", type: "hymn"});
    hymnCollection.insert({number: 140, numberText: "140", name: "Did You Think to Pray?", type: "hymn"});
    hymnCollection.insert({number: 141, numberText: "141", name: "Jesus, the Very Thought of Thee", type: "hymn"});
    hymnCollection.insert({number: 142, numberText: "142", name: "Sweet Hour of Prayer", type: "hymn"});
    hymnCollection.insert({number: 143, numberText: "143", name: "Let the Holy Spirit Guide", type: "hymn"});
    hymnCollection.insert({number: 144, numberText: "144", name: "Secret Prayer", type: "hymn"});
    hymnCollection.insert({number: 145, numberText: "145", name: "Prayer Is the Soul's Sincere Desire", type: "hymn"});
    hymnCollection.insert({number: 146, numberText: "146", name: "Gently Raise the Sacred Strain", type: "hymn"});
    hymnCollection.insert({number: 147, numberText: "147", name: "Sweet Is the Work", type: "hymn"});
    hymnCollection.insert({number: 148, numberText: "148", name: "Sabbath Day", type: "hymn"});
    hymnCollection.insert({number: 149, numberText: "149", name: "As the Dew from Heaven Distilling", type: "hymn"});
    hymnCollection.insert({number: 150, numberText: "150", name: "O Thou Kind and Gracious Father", type: "hymn"});
    hymnCollection.insert({number: 151, numberText: "151", name: "We Meet, Dear Lord", type: "hymn"});
    hymnCollection.insert({number: 152, numberText: "152", name: "God Be with You Till We Meet Again", type: "hymn"});
    hymnCollection.insert({number: 153, numberText: "153", name: "Lord, We Ask Thee Ere We Part", type: "hymn"});
    hymnCollection.insert({number: 154, numberText: "154", name: "Father, This Hour Has Been One of Joy", type: "hymn"});
    hymnCollection.insert({number: 155, numberText: "155", name: "We Have Partaken of Thy Love", type: "hymn"});
    hymnCollection.insert({number: 156, numberText: "156", name: "Sing We Now at Parting", type: "hymn"});
    hymnCollection.insert({number: 157, numberText: "157", name: "Thy Spirit, Lord, Has Stirred Our Souls", type: "hymn"});
    hymnCollection.insert({number: 158, numberText: "158", name: "Before Thee, Lord, I Bow My Head", type: "hymn"});
    hymnCollection.insert({number: 159, numberText: "159", name: "Now the Day Is Over", type: "hymn"});
    hymnCollection.insert({number: 160, numberText: "160", name: "Softly Now the Light of Day", type: "hymn"});
    hymnCollection.insert({number: 161, numberText: "161", name: "The Lord Be with Us", type: "hymn"});
    hymnCollection.insert({number: 162, numberText: "162", name: "Lord, We Come before Thee Now", type: "hymn"});
    hymnCollection.insert({number: 163, numberText: "163", name: "Lord, Dismiss Us with Thy Blessing", type: "hymn"});
    hymnCollection.insert({number: 164, numberText: "164", name: "Great God, to Thee My Evening Song", type: "hymn"});
    hymnCollection.insert({number: 165, numberText: "165", name: "Abide with Me; 'Tis Eventide", type: "hymn"});
    hymnCollection.insert({number: 166, numberText: "166", name: "Abide with Me!", type: "hymn"});
    hymnCollection.insert({number: 167, numberText: "167", name: "Come, Let Us Sing an Evening Hymn", type: "hymn"});
    hymnCollection.insert({number: 168, numberText: "168", name: "As the Shadows Fall", type: "hymn"});
    hymnCollection.insert({number: 169, numberText: "169", name: "As Now We Take the Sacrament", type: "hymn"});
    hymnCollection.insert({number: 170, numberText: "170", name: "God, Our Father, Hear Us Pray", type: "hymn"});
    hymnCollection.insert({number: 171, numberText: "171", name: "With Humble Heart", type: "hymn"});
    hymnCollection.insert({number: 172, numberText: "172", name: "In Humility, Our Savior", type: "hymn"});
    hymnCollection.insert({number: 173, numberText: "173", name: "While of These Emblems We Partake", type: "hymn"});
    hymnCollection.insert({number: 174, numberText: "174", name: "While of These Emblems We Partake", type: "hymn"});
    hymnCollection.insert({number: 175, numberText: "175", name: "O God, the Eternal Father", type: "hymn"});
    hymnCollection.insert({number: 176, numberText: "176", name: "Tis Sweet to Sing the Matchless Love", type: "hymn"});
    hymnCollection.insert({number: 177, numberText: "177", name: "Tis Sweet To Sing the Matchless Love", type: "hymn"});
    hymnCollection.insert({number: 178, numberText: "178", name: "O Lord of Hosts", type: "hymn"});
    hymnCollection.insert({number: 179, numberText: "179", name: "Again, Our Dear Redeeming Lord", type: "hymn"});
    hymnCollection.insert({number: 180, numberText: "180", name: "Father in Heaven, We Do Believe", type: "hymn"});
    hymnCollection.insert({number: 181, numberText: "181", name: "Jesus of Nazareth, Savior and King", type: "hymn"});
    hymnCollection.insert({number: 182, numberText: "182", name: "We'll Sing All Hail to Jesus' Name", type: "hymn"});
    hymnCollection.insert({number: 183, numberText: "183", name: "In Remembrance of Thy Suffering", type: "hymn"});
    hymnCollection.insert({number: 184, numberText: "184", name: "Upon the Cross of Calvary", type: "hymn"});
    hymnCollection.insert({number: 185, numberText: "185", name: "Reverently and Meekly Now", type: "hymn"});
    hymnCollection.insert({number: 186, numberText: "186", name: "Again We Meet around the Board", type: "hymn"});
    hymnCollection.insert({number: 187, numberText: "187", name: "God Loved Us, So He Sent His Son", type: "hymn"});
    hymnCollection.insert({number: 188, numberText: "188", name: "Thy Will, O Lord, Be Done", type: "hymn"});
    hymnCollection.insert({number: 189, numberText: "189", name: "O Thou, Before the World Began", type: "hymn"});
    hymnCollection.insert({number: 190, numberText: "190", name: "In Memory of the Crucified", type: "hymn"});
    hymnCollection.insert({number: 191, numberText: "191", name: "Behold the Great Redeemer Die", type: "hymn"});
    hymnCollection.insert({number: 192, numberText: "192", name: "He Died! The Great Redeemer Died", type: "hymn"});
    hymnCollection.insert({number: 193, numberText: "193", name: "I Stand All Amazed", type: "hymn"});
    hymnCollection.insert({number: 194, numberText: "194", name: "There Is a Green Hill Far Away", type: "hymn"});
    hymnCollection.insert({number: 195, numberText: "195", name: "How Great the Wisdom and the Love", type: "hymn"});
    hymnCollection.insert({number: 196, numberText: "196", name: "Jesus, Once of Humble Birth", type: "hymn"});
    hymnCollection.insert({number: 197, numberText: "197", name: "O Savior, Thou Who Wearest a Crown", type: "hymn"});
    hymnCollection.insert({number: 198, numberText: "198", name: "That Easter Morn", type: "hymn"});
    hymnCollection.insert({number: 199, numberText: "199", name: "He Is Risen!", type: "hymn"});
    hymnCollection.insert({number: 200, numberText: "200", name: "Christ the Lord Is Risen Today", type: "hymn"});
    hymnCollection.insert({number: 201, numberText: "201", name: "Joy to the World", type: "hymn"});
    hymnCollection.insert({number: 202, numberText: "202", name: "Oh, Come, All Ye Faithful", type: "hymn"});
    hymnCollection.insert({number: 203, numberText: "203", name: "Angels We Have Heard on High", type: "hymn"});
    hymnCollection.insert({number: 204, numberText: "204", name: "Silent Night", type: "hymn"});
    hymnCollection.insert({number: 205, numberText: "205", name: "Once in Royal David's City", type: "hymn"});
    hymnCollection.insert({number: 206, numberText: "206", name: "Away in a Manger", type: "hymn"});
    hymnCollection.insert({number: 207, numberText: "207", name: "It Came upon the Midnight Clear", type: "hymn"});
    hymnCollection.insert({number: 208, numberText: "208", name: "O Little Town of Bethlehem", type: "hymn"});
    hymnCollection.insert({number: 209, numberText: "209", name: "Hark! The Herald Angels Sing", type: "hymn"});
    hymnCollection.insert({number: 210, numberText: "210", name: "With Wondering Awe", type: "hymn"});
    hymnCollection.insert({number: 211, numberText: "211", name: "While Shepherds Watched Their Flocks", type: "hymn"});
    hymnCollection.insert({number: 212, numberText: "212", name: "Far, Far Away on Judea's Plains", type: "hymn"});
    hymnCollection.insert({number: 213, numberText: "213", name: "The First Noel", type: "hymn"});
    hymnCollection.insert({number: 214, numberText: "214", name: "I Heard the Bells on Christmas Day", type: "hymn"});
    hymnCollection.insert({number: 215, numberText: "215", name: "Ring Out, Wild Bells", type: "hymn"});
    hymnCollection.insert({number: 216, numberText: "216", name: "We Are Sowing", type: "hymn"});
    hymnCollection.insert({number: 217, numberText: "217", name: "Come, Let Us Anew", type: "hymn"});
    hymnCollection.insert({number: 218, numberText: "218", name: "We Give Thee But Thine Own", type: "hymn"});
    hymnCollection.insert({number: 219, numberText: "219", name: "Because I Have Been Given Much", type: "hymn"});
    hymnCollection.insert({number: 220, numberText: "220", name: "Lord, I Would Follow Thee", type: "hymn"});
    hymnCollection.insert({number: 221, numberText: "221", name: "Dear to the Heart of the Shepherd", type: "hymn"});
    hymnCollection.insert({number: 222, numberText: "222", name: "Hear Thou Our Hymn, O Lord", type: "hymn"});
    hymnCollection.insert({number: 223, numberText: "223", name: "Have I Done Any Good?", type: "hymn"});
    hymnCollection.insert({number: 224, numberText: "224", name: "I Have Work Enough to Do", type: "hymn"});
    hymnCollection.insert({number: 225, numberText: "225", name: "We Are Marching On to Glory", type: "hymn"});
    hymnCollection.insert({number: 226, numberText: "226", name: "Improve the Shining Moments", type: "hymn"});
    hymnCollection.insert({number: 227, numberText: "227", name: "There Is Sunshine in My Soul Today", type: "hymn"});
    hymnCollection.insert({number: 228, numberText: "228", name: "You Can Make the Pathway Bright", type: "hymn"});
    hymnCollection.insert({number: 229, numberText: "229", name: "Today, While the Sun Shines", type: "hymn"});
    hymnCollection.insert({number: 230, numberText: "230", name: "Scatter Sunshine", type: "hymn"});
    hymnCollection.insert({number: 231, numberText: "231", name: "Father, Cheer Our Souls Tonight", type: "hymn"});
    hymnCollection.insert({number: 232, numberText: "232", name: "Let Us Oft Speak Kind Words", type: "hymn"});
    hymnCollection.insert({number: 233, numberText: "233", name: "Nay, Speak No Ill", type: "hymn"});
    hymnCollection.insert({number: 234, numberText: "234", name: "Jesus, Mighty King in Zion", type: "hymn"});
    hymnCollection.insert({number: 235, numberText: "235", name: "Should You Feel Inclined to Censure", type: "hymn"});
    hymnCollection.insert({number: 236, numberText: "236", name: "Lord, Accept into Thy Kingdom", type: "hymn"});
    hymnCollection.insert({number: 237, numberText: "237", name: "Do What Is Right", type: "hymn"});
    hymnCollection.insert({number: 238, numberText: "238", name: "Behold Thy Sons and Daughters, Lord", type: "hymn"});
    hymnCollection.insert({number: 239, numberText: "239", name: "Choose the Right", type: "hymn"});
    hymnCollection.insert({number: 240, numberText: "240", name: "Know This, That Every Soul Is Free", type: "hymn"});
    hymnCollection.insert({number: 241, numberText: "241", name: "Count Your Blessings", type: "hymn"});
    hymnCollection.insert({number: 242, numberText: "242", name: "Praise God, from Whom All Blessings Flow", type: "hymn"});
    hymnCollection.insert({number: 243, numberText: "243", name: "Let Us All Press On", type: "hymn"});
    hymnCollection.insert({number: 244, numberText: "244", name: "Come Along, Come Along", type: "hymn"});
    hymnCollection.insert({number: 245, numberText: "245", name: "This House We Dedicate to Thee", type: "hymn"});
    hymnCollection.insert({number: 246, numberText: "246", name: "Onward, Christian Soldiers", type: "hymn"});
    hymnCollection.insert({number: 247, numberText: "247", name: "We Love Thy House, O God", type: "hymn"});
    hymnCollection.insert({number: 248, numberText: "248", name: "Up, Awake, Ye Defenders of Zion", type: "hymn"});
    hymnCollection.insert({number: 249, numberText: "249", name: "Called to Serve", type: "hymn"});
    hymnCollection.insert({number: 250, numberText: "250", name: "We Are All Enlisted", type: "hymn"});
    hymnCollection.insert({number: 251, numberText: "251", name: "Behold! A Royal Army", type: "hymn"});
    hymnCollection.insert({number: 252, numberText: "252", name: "Put Your Shoulder to the Wheel", type: "hymn"});
    hymnCollection.insert({number: 253, numberText: "253", name: "Like Ten Thousand Legions Marching", type: "hymn"});
    hymnCollection.insert({number: 254, numberText: "254", name: "True to the Faith", type: "hymn"});
    hymnCollection.insert({number: 255, numberText: "255", name: "Carry On", type: "hymn"});
    hymnCollection.insert({number: 256, numberText: "256", name: "As Zion's Youth in Latter Days", type: "hymn"});
    hymnCollection.insert({number: 257, numberText: "257", name: "Rejoice! A Glorious Sound Is Heard", type: "hymn"});
    hymnCollection.insert({number: 258, numberText: "258", name: "O Thou Rock of Our Salvation", type: "hymn"});
    hymnCollection.insert({number: 259, numberText: "259", name: "Hope of Israel", type: "hymn"});
    hymnCollection.insert({number: 260, numberText: "260", name: "Who's on the Lord's Side?", type: "hymn"});
    hymnCollection.insert({number: 261, numberText: "261", name: "Thy Servants Are Prepared", type: "hymn"});
    hymnCollection.insert({number: 262, numberText: "262", name: "Go, Ye Messengers of Glory", type: "hymn"});
    hymnCollection.insert({number: 263, numberText: "263", name: "Go Forth with Faith", type: "hymn"});
    hymnCollection.insert({number: 264, numberText: "264", name: "Hark, All Ye Nations!", type: "hymn"});
    hymnCollection.insert({number: 265, numberText: "265", name: "Arise, O God, and Shine", type: "hymn"});
    hymnCollection.insert({number: 266, numberText: "266", name: "The Time Is Far Spent", type: "hymn"});
    hymnCollection.insert({number: 267, numberText: "267", name: "How Wondrous and Great", type: "hymn"});
    hymnCollection.insert({number: 268, numberText: "268", name: "Come, All Whose Souls Are Lighted", type: "hymn"});
    hymnCollection.insert({number: 269, numberText: "269", name: "Jehovah, Lord of Heaven and Earth", type: "hymn"});
    hymnCollection.insert({number: 270, numberText: "270", name: "I'll Go Where You Want Me to Go", type: "hymn"});
    hymnCollection.insert({number: 271, numberText: "271", name: "Oh, Holy Words of Truth and Love", type: "hymn"});
    hymnCollection.insert({number: 272, numberText: "272", name: "Oh Say, What Is Truth?", type: "hymn"});
    hymnCollection.insert({number: 273, numberText: "273", name: "Truth Reflects upon Our Senses", type: "hymn"});
    hymnCollection.insert({number: 274, numberText: "274", name: "The Iron Rod", type: "hymn"});
    hymnCollection.insert({number: 275, numberText: "275", name: "Men Are That They Might Have Joy", type: "hymn"});
    hymnCollection.insert({number: 276, numberText: "276", name: "Come Away to the Sunday School", type: "hymn"});
    hymnCollection.insert({number: 277, numberText: "277", name: "As I Search the Holy Scriptures", type: "hymn"});
    hymnCollection.insert({number: 278, numberText: "278", name: "Thanks for the Sabbath School", type: "hymn"});
    hymnCollection.insert({number: 279, numberText: "279", name: "Thy Holy Word", type: "hymn"});
    hymnCollection.insert({number: 280, numberText: "280", name: "Welcome, Welcome, Sabbath Morning", type: "hymn"});
    hymnCollection.insert({number: 281, numberText: "281", name: "Help Me Teach with Inspiration", type: "hymn"});
    hymnCollection.insert({number: 282, numberText: "282", name: "We Meet Again in Sabbath School", type: "hymn"});
    hymnCollection.insert({number: 283, numberText: "283", name: "The Glorious Gospel Light Has Shone", type: "hymn"});
    hymnCollection.insert({number: 284, numberText: "284", name: "If You Could Hie to Kolob", type: "hymn"});
    hymnCollection.insert({number: 285, numberText: "285", name: "God Moves in a Mysterious Way", type: "hymn"});
    hymnCollection.insert({number: 286, numberText: "286", name: "Oh, What Songs of the Heart", type: "hymn"});
    hymnCollection.insert({number: 287, numberText: "287", name: "Rise, Ye Saints, and Temples Enter", type: "hymn"});
    hymnCollection.insert({number: 288, numberText: "288", name: "How Beautiful Thy Temples, Lord", type: "hymn"});
    hymnCollection.insert({number: 289, numberText: "289", name: "Holy Temples on Mount Zion", type: "hymn"});
    hymnCollection.insert({number: 290, numberText: "290", name: "Rejoice, Ye Saints of Latter Days", type: "hymn"});
    hymnCollection.insert({number: 291, numberText: "291", name: "Turn Your Hearts", type: "hymn"});
    hymnCollection.insert({number: 292, numberText: "292", name: "O My Father", type: "hymn"});
    hymnCollection.insert({number: 293, numberText: "293", name: "Each Life That Touches Ours for Good", type: "hymn"});
    hymnCollection.insert({number: 294, numberText: "294", name: "Love at Home", type: "hymn"});
    hymnCollection.insert({number: 295, numberText: "295", name: "O Love That Glorifies the Son", type: "hymn"});
    hymnCollection.insert({number: 296, numberText: "296", name: "Our Father, by Whose Name", type: "hymn"});
    hymnCollection.insert({number: 297, numberText: "297", name: "From Homes of Saints Glad Songs Arise", type: "hymn"});
    hymnCollection.insert({number: 298, numberText: "298", name: "Home Can Be a Heaven on Earth", type: "hymn"});
    hymnCollection.insert({number: 299, numberText: "299", name: "Children of Our Heavenly Father", type: "hymn"});
    hymnCollection.insert({number: 300, numberText: "300", name: "Families Can Be Together Forever", type: "hymn"});
    hymnCollection.insert({number: 301, numberText: "301", name: "I Am a Child of God", type: "hymn"});
    hymnCollection.insert({number: 302, numberText: "302", name: "I Know My Father Lives", type: "hymn"});
    hymnCollection.insert({number: 303, numberText: "303", name: "Keep the Commandments", type: "hymn"});
    hymnCollection.insert({number: 304, numberText: "304", name: "Teach Me to Walk in the Light", type: "hymn"});
    hymnCollection.insert({number: 305, numberText: "305", name: "The Light Divine", type: "hymn"});
    hymnCollection.insert({number: 306, numberText: "306", name: "God's Daily Care", type: "hymn"});
    hymnCollection.insert({number: 307, numberText: "307", name: "In Our Lovely Deseret", type: "hymn"});
    hymnCollection.insert({number: 308, numberText: "308", name: "Love One Another", type: "hymn"});
    hymnCollection.insert({number: 309, numberText: "309", name: "As Sisters in Zion (Women)", type: "hymn"});
    hymnCollection.insert({number: 310, numberText: "310", name: "A Key Was Turned in Latter Days (Women)", type: "hymn"});
    hymnCollection.insert({number: 311, numberText: "311", name: "We Meet Again as Sisters (Women)", type: "hymn"});
    hymnCollection.insert({number: 312, numberText: "312", name: "We Ever Pray for Thee (Women)", type: "hymn"});
    hymnCollection.insert({number: 313, numberText: "313", name: "God Is Love (Women)", type: "hymn"});
    hymnCollection.insert({number: 314, numberText: "314", name: "How Gentle God's Commands (Women)", type: "hymn"});
    hymnCollection.insert({number: 315, numberText: "315", name: "Jesus, the Very Thought of Thee (Women)", type: "hymn"});
    hymnCollection.insert({number: 316, numberText: "316", name: "The Lord Is My Shepherd (Women)", type: "hymn"});
    hymnCollection.insert({number: 317, numberText: "317", name: "Sweet Is the Work (Women)", type: "hymn"});
    hymnCollection.insert({number: 318, numberText: "318", name: "Love at Home (Women)", type: "hymn"});
    hymnCollection.insert({number: 319, numberText: "319", name: "Ye Elders of Israel (Men)", type: "hymn"});
    hymnCollection.insert({number: 320, numberText: "320", name: "The Priesthood of Our Lord (Men)", type: "hymn"});
    hymnCollection.insert({number: 321, numberText: "321", name: "Ye Who Are Called to Labor (Men)", type: "hymn"});
    hymnCollection.insert({number: 322, numberText: "322", name: "Come, All Ye Sons of God (Men)", type: "hymn"});
    hymnCollection.insert({number: 323, numberText: "323", name: "Rise Up, O Men of God (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 324, numberText: "324", name: "Rise Up, O Men of God (Men)", type: "hymn"});
    hymnCollection.insert({number: 325, numberText: "325", name: "See the Mighty Priesthood Gathered (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 326, numberText: "326", name: "Come, Come, Ye Saints (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 327, numberText: "327", name: "Go, Ye Messengers of Heaven (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 328, numberText: "328", name: "An Angel from on High", type: "hymn"});
    hymnCollection.insert({number: 329, numberText: "329", name: "Thy Servants Are Prepared (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 330, numberText: "330", name: "See, the Mighty Angel Flying (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 331, numberText: "331", name: "Oh Say, What Is Truth? (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 332, numberText: "332", name: "Come, O Thou King of Kings (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 333, numberText: "333", name: "High on the Mountain Top (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 334, numberText: "334", name: "I Need Thee Every Hour (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 335, numberText: "335", name: "Brightly Beams Our Father's Mercy (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 336, numberText: "336", name: "School Thy Feelings (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 337, numberText: "337", name: "O Home Beloved (Men's Choir)", type: "hymn"});
    hymnCollection.insert({number: 338, numberText: "338", name: "America the Beautiful", type: "hymn"});
    hymnCollection.insert({number: 339, numberText: "339", name: "My Country, 'Tis of Thee", type: "hymn"});
    hymnCollection.insert({number: 340, numberText: "340", name: "The Star Spangled Banner", type: "hymn"});
    hymnCollection.insert({number: 341, numberText: "341", name: "God Save the King", type: "hymn"});

    hymnCollection.insert({number: 2, numberText: "2", name: "I Am a Child of God", type: "primarySong"});
    hymnCollection.insert({number: 4, numberText: "4", name: "I Lived in Heaven", type: "primarySong"});
    hymnCollection.insert({number: 5, numberText: "5", name: "I Know My Father Lives", type: "primarySong"});
    hymnCollection.insert({number: 6, numberText: "6", name: "Thanks to Thee", type: "primarySong"});
    hymnCollection.insert({number: 7, numberText: "7", name: "I Thank Thee, Dear Father", type: "primarySong"});
    hymnCollection.insert({number: 8, numberText: "8", name: "Father, We Thank Thee for the Night", type: "primarySong"});
    hymnCollection.insert({number: 9, numberText: "9", name: "Can a Little Child like Me?", type: "primarySong"});
    hymnCollection.insert({number: 10, numberText: "10", name: "Thank Thee for Everything", type: "primarySong"});
    hymnCollection.insert({number: 11, numberText: "11", name: "I'm Thankful to Be Me", type: "primarySong"});
    hymnCollection.insert({number: 12, numberText: "12", name: "A Child's Prayer", type: "primarySong"});
    hymnCollection.insert({number: 14, numberText: "14", name: "I Pray in Faith", type: "primarySong"});
    hymnCollection.insert({number: 15, numberText: "15", name: "If with All Your Hearts", type: "primarySong"});
    hymnCollection.insert({number: 16, numberText: "16", name: "Children All Over the World", type: "primarySong"});
    hymnCollection.insert({number: 18, numberText: "18", name: "I Need My Heavenly Father", type: "primarySong"});
    hymnCollection.insert({number: 19, numberText: "19", name: "Heavenly Father, Now I Pray", type: "primarySong"});
    hymnCollection.insert({number: 20, numberText: "20", name: "A Song of Thanks", type: "primarySong"});
    hymnCollection.insert({number: 20, numberText: "20", name: "Thanks to Our Father", type: "primarySong"});
    hymnCollection.insert({number: 21, numberText: "21", name: "For Thy Bounteous Blessings (Round)", type: "primarySong"});
    hymnCollection.insert({number: 21, numberText: "21", name: "For Health and Strength (Round)", type: "primarySong"});
    hymnCollection.insert({number: 22, numberText: "22", name: "A Prayer", type: "primarySong"});
    hymnCollection.insert({number: 22, numberText: "22", name: "A Prayer Song", type: "primarySong"});
    hymnCollection.insert({number: 23, numberText: "23", name: "Heavenly Father, While I Pray", type: "primarySong"});
    hymnCollection.insert({number: 23, numberText: "23", name: "Father Up Above", type: "primarySong"});
    hymnCollection.insert({number: 24, numberText: "24", name: "Thank Thee, Father", type: "primarySong"});
    hymnCollection.insert({number: 25, numberText: "25", name: "We Bow Our Heads", type: "primarySong"});
    hymnCollection.insert({number: 25, numberText: "25", name: "I Love to Pray", type: "primarySong"});
    hymnCollection.insert({number: 26, numberText: "26", name: "Reverently, Quietly", type: "primarySong"});
    hymnCollection.insert({number: 27, numberText: "27", name: "We Are Reverent", type: "primarySong"});
    hymnCollection.insert({number: 27, numberText: "27", name: "Reverence", type: "primarySong"});
    hymnCollection.insert({number: 28, numberText: "28", name: "I Will Try to Be Reverent", type: "primarySong"});
    hymnCollection.insert({number: 28, numberText: "28", name: "I Want to Be Reverent", type: "primarySong"});
    hymnCollection.insert({number: 29, numberText: "29", name: "Father, I Will Reverent Be", type: "primarySong"});
    hymnCollection.insert({number: 30, numberText: "30", name: "Our Chapel Is a Sacred Place", type: "primarySong"});
    hymnCollection.insert({number: 30, numberText: "30", name: "This Is God's House", type: "primarySong"});
    hymnCollection.insert({number: 31, numberText: "31", name: "Reverence Is Love", type: "primarySong"});
    hymnCollection.insert({number: 34, numberText: "34", name: "He Sent His Son", type: "primarySong"});
    hymnCollection.insert({number: 36, numberText: "36", name: "Samuel Tells of the Baby Jesus", type: "primarySong"});
    hymnCollection.insert({number: 37, numberText: "37", name: "Stars Were Gleaming", type: "primarySong"});
    hymnCollection.insert({number: 38, numberText: "38", name: "When Joseph Went to Bethlehem", type: "primarySong"});
    hymnCollection.insert({number: 39, numberText: "39", name: "Little Jesus", type: "primarySong"});
    hymnCollection.insert({number: 40, numberText: "40", name: "The Shepherd's Carol (Round)", type: "primarySong"});
    hymnCollection.insert({number: 40, numberText: "40", name: "There Was Starlight on the Hillside", type: "primarySong"});
    hymnCollection.insert({number: 41, numberText: "41", name: "Once within a Lowly Stable", type: "primarySong"});
    hymnCollection.insert({number: 42, numberText: "42", name: "Away in a Manger", type: "primarySong"});
    hymnCollection.insert({number: 44, numberText: "44", name: "Mary's Lullaby", type: "primarySong"});
    hymnCollection.insert({number: 46, numberText: "46", name: "Who Is the Child?", type: "primarySong"});
    hymnCollection.insert({number: 47, numberText: "47", name: "Sleep, Little Jesus", type: "primarySong"});
    hymnCollection.insert({number: 48, numberText: "48", name: "Oh, Hush Thee, My Baby", type: "primarySong"});
    hymnCollection.insert({number: 50, numberText: "50", name: "Picture a Christmas", type: "primarySong"});
    hymnCollection.insert({number: 51, numberText: "51", name: "Have a Very Merry Christmas!", type: "primarySong"});
    hymnCollection.insert({number: 52, numberText: "52", name: "The Nativity Song", type: "primarySong"});
    hymnCollection.insert({number: 54, numberText: "54", name: "Christmas Bells", type: "primarySong"});
    hymnCollection.insert({number: 55, numberText: "55", name: "Jesus Once Was a Little Child", type: "primarySong"});
    hymnCollection.insert({number: 56, numberText: "56", name: "I Think When I Read That Sweet Story", type: "primarySong"});
    hymnCollection.insert({number: 57, numberText: "57", name: "Tell Me the Stories of Jesus", type: "primarySong"});
    hymnCollection.insert({number: 58, numberText: "58", name: "Little Lambs So White and Fair", type: "primarySong"});
    hymnCollection.insert({number: 58, numberText: "58", name: "Jesus Is Our Loving Friend", type: "primarySong"});
    hymnCollection.insert({number: 59, numberText: "59", name: "Jesus Loved the Little Children", type: "primarySong"});
    hymnCollection.insert({number: 60, numberText: "60", name: "Jesus Wants Me for a Sunbeam", type: "primarySong"});
    hymnCollection.insert({number: 61, numberText: "61", name: "Jesus Said Love Everyone", type: "primarySong"});
    hymnCollection.insert({number: 62, numberText: "62", name: "Beautiful Savior (Crusader's Hymn)", type: "primarySong"});
    hymnCollection.insert({number: 64, numberText: "64", name: "Did Jesus Really Live Again?", type: "primarySong"});
    hymnCollection.insert({number: 65, numberText: "65", name: "He Died That We Might Live Again", type: "primarySong"});
    hymnCollection.insert({number: 66, numberText: "66", name: "Hosanna", type: "primarySong"});
    hymnCollection.insert({number: 68, numberText: "68", name: "Easter Hosanna", type: "primarySong"});
    hymnCollection.insert({number: 70, numberText: "70", name: "Jesus Has Risen", type: "primarySong"});
    hymnCollection.insert({number: 71, numberText: "71", name: "To Think about Jesus", type: "primarySong"});
    hymnCollection.insert({number: 72, numberText: "72", name: "The Sacrament", type: "primarySong"});
    hymnCollection.insert({number: 73, numberText: "73", name: "Before I Take the Sacrament", type: "primarySong"});
    hymnCollection.insert({number: 73, numberText: "73", name: "Help Us, O God, to Understand", type: "primarySong"});
    hymnCollection.insert({number: 74, numberText: "74", name: "I Feel My Savior's Love", type: "primarySong"});
    hymnCollection.insert({number: 76, numberText: "76", name: "This Is My Beloved Son", type: "primarySong"});
    hymnCollection.insert({number: 77, numberText: "77", name: "The Church of Jesus Christ", type: "primarySong"});
    hymnCollection.insert({number: 78, numberText: "78", name: "I'm Trying to Be like Jesus", type: "primarySong"});
    hymnCollection.insert({number: 80, numberText: "80", name: "Had I Been a Child", type: "primarySong"});
    hymnCollection.insert({number: 82, numberText: "82", name: "When He Comes Again", type: "primarySong"});
    hymnCollection.insert({number: 86, numberText: "86", name: "An Angel Came to Joseph Smith", type: "primarySong"});
    hymnCollection.insert({number: 86, numberText: "86", name: "The Golden Plates", type: "primarySong"});
    hymnCollection.insert({number: 87, numberText: "87", name: "The Sacred Grove", type: "primarySong"});
    hymnCollection.insert({number: 88, numberText: "88", name: "On a Golden Springtime", type: "primarySong"});
    hymnCollection.insert({number: 89, numberText: "89", name: "The Priesthood Is Restored", type: "primarySong"});
    hymnCollection.insert({number: 90, numberText: "90", name: "Truth from Elijah", type: "primarySong"});
    hymnCollection.insert({number: 92, numberText: "92", name: "The Hearts of the Children", type: "primarySong"});
    hymnCollection.insert({number: 94, numberText: "94", name: "Family History ", type: "primarySong"});
    hymnCollection.insert({number: 95, numberText: "95", name: "I Love to See the Temple", type: "primarySong"});
    hymnCollection.insert({number: 96, numberText: "96", name: "Faith", type: "primarySong"});
    hymnCollection.insert({number: 97, numberText: "97", name: "God's Love", type: "primarySong"});
    hymnCollection.insert({number: 98, numberText: "98", name: "Repentance", type: "primarySong"});
    hymnCollection.insert({number: 99, numberText: "99", name: "Help Me, Dear Father", type: "primarySong"});
    hymnCollection.insert({number: 100, numberText: "100", name: "Baptism", type: "primarySong"});
    hymnCollection.insert({number: 102, numberText: "102", name: "When Jesus Christ Was Baptized", type: "primarySong"});
    hymnCollection.insert({number: 103, numberText: "103", name: "When I Am Baptized", type: "primarySong"});
    hymnCollection.insert({number: 104, numberText: "104", name: "I Like My Birthdays", type: "primarySong"});
    hymnCollection.insert({number: 105, numberText: "105", name: "The Holy Ghost", type: "primarySong"});
    hymnCollection.insert({number: 106, numberText: "106", name: "The Still Small Voice", type: "primarySong"});
    hymnCollection.insert({number: 107, numberText: "107", name: "Listen, Listen (Round)", type: "primarySong"});
    hymnCollection.insert({number: 108, numberText: "108", name: "Seek the Lord Early", type: "primarySong"});
    hymnCollection.insert({number: 109, numberText: "109", name: "Search, Ponder, and Pray", type: "primarySong"});
    hymnCollection.insert({number: 110, numberText: "110", name: "Follow the Prophet", type: "primarySong"});
    hymnCollection.insert({number: 112, numberText: "112", name: "The Commandments", type: "primarySong"});
    hymnCollection.insert({number: 114, numberText: "114", name: "The Books in the Old Testament", type: "primarySong"});
    hymnCollection.insert({number: 116, numberText: "116", name: "The Books in the New Testament", type: "primarySong"});
    hymnCollection.insert({number: 118, numberText: "118", name: "Book of Mormon Stories", type: "primarySong"});
    hymnCollection.insert({number: 119, numberText: "119", name: "The Books in the Book of Mormon", type: "primarySong"});
    hymnCollection.insert({number: 120, numberText: "120", name: "Nephi's Courage", type: "primarySong"});
    hymnCollection.insert({number: 122, numberText: "122", name: "The Second Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 122, numberText: "122", name: "The First Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 123, numberText: "123", name: "The Third Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 124, numberText: "124", name: "The Fourth Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 125, numberText: "125", name: "The Fifth Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 126, numberText: "126", name: "The Sixth Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 126, numberText: "126", name: "The Seventh Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 127, numberText: "127", name: "The Eighth Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 128, numberText: "128", name: "The Ninth Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 128, numberText: "128", name: "The Tenth Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 130, numberText: "130", name: "The Eleventh Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 131, numberText: "131", name: "The Twelfth Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 132, numberText: "132", name: "The Thirteenth Article of Faith", type: "primarySong"});
    hymnCollection.insert({number: 134, numberText: "134", name: "Latter", type: "primarySong"});
    hymnCollection.insert({number: 135, numberText: "135", name: "Our Bishop", type: "primarySong"});
    hymnCollection.insert({number: 136, numberText: "136", name: "Love One Another", type: "primarySong"});
    hymnCollection.insert({number: 138, numberText: "138", name: "Where Love Is", type: "primarySong"});
    hymnCollection.insert({number: 140, numberText: "140", name: "I'll Walk with You", type: "primarySong"});
    hymnCollection.insert({number: 142, numberText: "142", name: "Every Star Is Different", type: "primarySong"});
    hymnCollection.insert({number: 144, numberText: "144", name: "Shine On", type: "primarySong"});
    hymnCollection.insert({number: 145, numberText: "145", name: "Kindness Begins with Me", type: "primarySong"});
    hymnCollection.insert({number: 145, numberText: "145", name: "A Special Gift Is Kindness", type: "primarySong"});
    hymnCollection.insert({number: 146, numberText: "146", name: "Keep the Commandments", type: "primarySong"});
    hymnCollection.insert({number: 148, numberText: "148", name: "I Want to Live the Gospel", type: "primarySong"});
    hymnCollection.insert({number: 149, numberText: "149", name: "I Believe in Being Honest", type: "primarySong"});
    hymnCollection.insert({number: 150, numberText: "150", name: "I Want to Give the Lord My Tenth", type: "primarySong"});
    hymnCollection.insert({number: 150, numberText: "150", name: "I'm Glad to Pay a Tithing", type: "primarySong"});
    hymnCollection.insert({number: 151, numberText: "151", name: "I Am Glad for Many Things", type: "primarySong"});
    hymnCollection.insert({number: 152, numberText: "152", name: "Hum Your Favorite Hymn", type: "primarySong"});
    hymnCollection.insert({number: 153, numberText: "153", name: "The Lord Gave Me a Temple", type: "primarySong"});
    hymnCollection.insert({number: 154, numberText: "154", name: "The Word of Wisdom", type: "primarySong"});
    hymnCollection.insert({number: 155, numberText: "155", name: "Remember the Sabbath Day", type: "primarySong"});
    hymnCollection.insert({number: 156, numberText: "156", name: "The Chapel Doors", type: "primarySong"});
    hymnCollection.insert({number: 157, numberText: "157", name: "When I Go to Church", type: "primarySong"});
    hymnCollection.insert({number: 158, numberText: "158", name: "Dare to Do Right", type: "primarySong"});
    hymnCollection.insert({number: 159, numberText: "159", name: "Stand for the Right", type: "primarySong"});
    hymnCollection.insert({number: 160, numberText: "160", name: "Choose the Right Way", type: "primarySong"});
    hymnCollection.insert({number: 161, numberText: "161", name: "I Pledge Myself to Love the Right", type: "primarySong"});
    hymnCollection.insert({number: 162, numberText: "162", name: "I Will Be Valiant", type: "primarySong"});
    hymnCollection.insert({number: 163, numberText: "163", name: "I Am like a Star", type: "primarySong"});
    hymnCollection.insert({number: 164, numberText: "164", name: "I Will Follow God's Plan", type: "primarySong"});
    hymnCollection.insert({number: 166, numberText: "166", name: "A Young Man Prepared", type: "primarySong"});
    hymnCollection.insert({number: 167, numberText: "167", name: "Go the Second Mile", type: "primarySong"});
    hymnCollection.insert({number: 168, numberText: "168", name: "I Want to Be a Missionary Now", type: "primarySong"});
    hymnCollection.insert({number: 169, numberText: "169", name: "I Hope They Call Me on a Mission", type: "primarySong"});
    hymnCollection.insert({number: 170, numberText: "170", name: "The Things I Do", type: "primarySong"});
    hymnCollection.insert({number: 172, numberText: "172", name: "We'll Bring the World His Truth (Army of Helaman)", type: "primarySong"});
    hymnCollection.insert({number: 174, numberText: "174", name: "Called to Serve", type: "primarySong"});
    hymnCollection.insert({number: 176, numberText: "176", name: "Tell Me, Dear Lord", type: "primarySong"});
    hymnCollection.insert({number: 177, numberText: "177", name: "Teach Me to Walk in the Light", type: "primarySong"});
    hymnCollection.insert({number: 178, numberText: "178", name: "Teacher, Do You Love Me?", type: "primarySong"});
    hymnCollection.insert({number: 180, numberText: "180", name: "How Dear to God Are Little Children (Appropriate for Parents and Leaders)", type: "primarySong"});
    hymnCollection.insert({number: 182, numberText: "182", name: "How Will They Know? (Appropriate for Parents and Leaders)", type: "primarySong"});
    hymnCollection.insert({number: 188, numberText: "188", name: "Families Can Be Together Forever", type: "primarySong"});
    hymnCollection.insert({number: 189, numberText: "189", name: "Family Prayer", type: "primarySong"});
    hymnCollection.insert({number: 190, numberText: "190", name: "Love Is Spoken Here", type: "primarySong"});
    hymnCollection.insert({number: 192, numberText: "192", name: "Home", type: "primarySong"});
    hymnCollection.insert({number: 193, numberText: "193", name: "Sing Your Way Home", type: "primarySong"});
    hymnCollection.insert({number: 194, numberText: "194", name: "The Family", type: "primarySong"});
    hymnCollection.insert({number: 195, numberText: "195", name: "Family Night", type: "primarySong"});
    hymnCollection.insert({number: 196, numberText: "196", name: "Saturday", type: "primarySong"});
    hymnCollection.insert({number: 197, numberText: "197", name: "A Happy Helper", type: "primarySong"});
    hymnCollection.insert({number: 197, numberText: "197", name: "Quickly I'll Obey", type: "primarySong"});
    hymnCollection.insert({number: 198, numberText: "198", name: "When We're Helping", type: "primarySong"});
    hymnCollection.insert({number: 198, numberText: "198", name: "A Happy Family", type: "primarySong"});
    hymnCollection.insert({number: 199, numberText: "199", name: "I Have a Family Tree", type: "primarySong"});
    hymnCollection.insert({number: 200, numberText: "200", name: "Grandmother", type: "primarySong"});
    hymnCollection.insert({number: 201, numberText: "201", name: "When Grandpa Comes", type: "primarySong"});
    hymnCollection.insert({number: 202, numberText: "202", name: "I Often Go Walking", type: "primarySong"});
    hymnCollection.insert({number: 203, numberText: "203", name: "My Mother Dear", type: "primarySong"});
    hymnCollection.insert({number: 204, numberText: "204", name: "Mother, Tell Me the Story", type: "primarySong"});
    hymnCollection.insert({number: 206, numberText: "206", name: "Dearest Mother, I Love You", type: "primarySong"});
    hymnCollection.insert({number: 206, numberText: "206", name: "Mother Dear", type: "primarySong"});
    hymnCollection.insert({number: 207, numberText: "207", name: "Mother, I Love You", type: "primarySong"});
    hymnCollection.insert({number: 208, numberText: "208", name: "The Dearest Names", type: "primarySong"});
    hymnCollection.insert({number: 209, numberText: "209", name: "Fathers", type: "primarySong"});
    hymnCollection.insert({number: 210, numberText: "210", name: "Daddy's Homecoming", type: "primarySong"});
    hymnCollection.insert({number: 211, numberText: "211", name: "My Dad", type: "primarySong"});
    hymnCollection.insert({number: 214, numberText: "214", name: "Pioneer Children Sang As They Walked", type: "primarySong"});
    hymnCollection.insert({number: 215, numberText: "215", name: "Pioneer Children Were Quick to Obey", type: "primarySong"});
    hymnCollection.insert({number: 216, numberText: "216", name: "Little Pioneer Children (Round)", type: "primarySong"});
    hymnCollection.insert({number: 217, numberText: "217", name: "Westward Ho!", type: "primarySong"});
    hymnCollection.insert({number: 218, numberText: "218", name: "To Be a Pioneer", type: "primarySong"});
    hymnCollection.insert({number: 219, numberText: "219", name: "The Oxcart", type: "primarySong"});
    hymnCollection.insert({number: 220, numberText: "220", name: "The Handcart Song", type: "primarySong"});
    hymnCollection.insert({number: 221, numberText: "221", name: "Covered Wagons", type: "primarySong"});
    hymnCollection.insert({number: 222, numberText: "222", name: "Whenever I Think about Pioneers", type: "primarySong"});
    hymnCollection.insert({number: 224, numberText: "224", name: "My Country", type: "primarySong"});
    hymnCollection.insert({number: 225, numberText: "225", name: "My Flag, My Flag", type: "primarySong"});
    hymnCollection.insert({number: 228, numberText: "228", name: "My Heavenly Father Loves Me", type: "primarySong"});
    hymnCollection.insert({number: 229, numberText: "229", name: "God Is Watching Over All", type: "primarySong"});
    hymnCollection.insert({number: 230, numberText: "230", name: "I Think the World Is Glorious", type: "primarySong"});
    hymnCollection.insert({number: 231, numberText: "231", name: "All Things Bright and Beautiful", type: "primarySong"});
    hymnCollection.insert({number: 232, numberText: "232", name: "Beauty Everywhere", type: "primarySong"});
    hymnCollection.insert({number: 233, numberText: "233", name: "The World Is So Lovely", type: "primarySong"});
    hymnCollection.insert({number: 234, numberText: "234", name: "Because God Loves Me", type: "primarySong"});
    hymnCollection.insert({number: 235, numberText: "235", name: "The World Is So Big", type: "primarySong"});
    hymnCollection.insert({number: 236, numberText: "236", name: "Give, Said the Little Stream", type: "primarySong"});
    hymnCollection.insert({number: 237, numberText: "237", name: "The Prophet Said to Plant a Garden", type: "primarySong"});
    hymnCollection.insert({number: 238, numberText: "238", name: "Springtime Is Coming", type: "primarySong"});
    hymnCollection.insert({number: 239, numberText: "239", name: "Because It's Spring", type: "primarySong"});
    hymnCollection.insert({number: 240, numberText: "240", name: "In the Leafy Treetops", type: "primarySong"});
    hymnCollection.insert({number: 241, numberText: "241", name: "Rain Is Falling All Around", type: "primarySong"});
    hymnCollection.insert({number: 241, numberText: "241", name: "Birds in the Tree", type: "primarySong"});
    hymnCollection.insert({number: 242, numberText: "242", name: "Popcorn Popping", type: "primarySong"});
    hymnCollection.insert({number: 243, numberText: "243", name: "Little Seeds Lie Fast Asleep", type: "primarySong"});
    hymnCollection.insert({number: 244, numberText: "244", name: "Little Purple Pansies", type: "primarySong"});
    hymnCollection.insert({number: 245, numberText: "245", name: "Oh, What Do You Do in the Summertime?", type: "primarySong"});
    hymnCollection.insert({number: 246, numberText: "246", name: "It's Autumntime", type: "primarySong"});
    hymnCollection.insert({number: 247, numberText: "247", name: "Autumn Day", type: "primarySong"});
    hymnCollection.insert({number: 248, numberText: "248", name: "Falling Snow", type: "primarySong"});
    hymnCollection.insert({number: 249, numberText: "249", name: "Once There Was a Snowman", type: "primarySong"});
    hymnCollection.insert({number: 252, numberText: "252", name: "Lift Up Your Voice and Sing", type: "primarySong"});
    hymnCollection.insert({number: 253, numberText: "253", name: "Sing a Song (Round)", type: "primarySong"});
    hymnCollection.insert({number: 253, numberText: "253", name: "Fun to Do", type: "primarySong"});
    hymnCollection.insert({number: 254, numberText: "254", name: "Hello, Friends!", type: "primarySong"});
    hymnCollection.insert({number: 254, numberText: "254", name: "Our Door Is Always Open (Round)", type: "primarySong"});
    hymnCollection.insert({number: 255, numberText: "255", name: "Come with Me to Primary (Round)", type: "primarySong"});
    hymnCollection.insert({number: 256, numberText: "256", name: "We Welcome You", type: "primarySong"});
    hymnCollection.insert({number: 258, numberText: "258", name: "Our Primary Colors", type: "primarySong"});
    hymnCollection.insert({number: 259, numberText: "259", name: "We're All Together Again", type: "primarySong"});
    hymnCollection.insert({number: 260, numberText: "260", name: "Hello Song", type: "primarySong"});
    hymnCollection.insert({number: 261, numberText: "261", name: "Here We Are Together", type: "primarySong"});
    hymnCollection.insert({number: 262, numberText: "262", name: "Friends Are Fun", type: "primarySong"});
    hymnCollection.insert({number: 263, numberText: "263", name: "We Are Different", type: "primarySong"});
    hymnCollection.insert({number: 264, numberText: "264", name: "Happy Song", type: "primarySong"});
    hymnCollection.insert({number: 265, numberText: "265", name: "Be Happy!", type: "primarySong"});
    hymnCollection.insert({number: 266, numberText: "266", name: "If You're Happy", type: "primarySong"});
    hymnCollection.insert({number: 267, numberText: "267", name: "Smiles", type: "primarySong"});
    hymnCollection.insert({number: 267, numberText: "267", name: "A Smile Is like the Sunshine", type: "primarySong"});
    hymnCollection.insert({number: 268, numberText: "268", name: "Two Little Eyes", type: "primarySong"});
    hymnCollection.insert({number: 269, numberText: "269", name: "I Have Two Ears", type: "primarySong"});
    hymnCollection.insert({number: 270, numberText: "270", name: "Two Happy Feet", type: "primarySong"});
    hymnCollection.insert({number: 271, numberText: "271", name: "I Wiggle", type: "primarySong"});
    hymnCollection.insert({number: 272, numberText: "272", name: "I Have Two Little Hands", type: "primarySong"});
    hymnCollection.insert({number: 273, numberText: "273", name: "My Hands", type: "primarySong"});
    hymnCollection.insert({number: 274, numberText: "274", name: "Roll Your Hands", type: "primarySong"});
    hymnCollection.insert({number: 275, numberText: "275", name: "To Get Quiet", type: "primarySong"});
    hymnCollection.insert({number: 275, numberText: "275", name: "Head, Shoulders, Knees, and Toes", type: "primarySong"});
    hymnCollection.insert({number: 276, numberText: "276", name: "Do As I'm Doing", type: "primarySong"});
    hymnCollection.insert({number: 277, numberText: "277", name: "Hinges", type: "primarySong"});
    hymnCollection.insert({number: 278, numberText: "278", name: "Stand Up", type: "primarySong"});
    hymnCollection.insert({number: 279, numberText: "279", name: "Oh, How We Love to Stand", type: "primarySong"});
    hymnCollection.insert({number: 280, numberText: "280", name: "Healthy, Wealthy, and Wise (Round)", type: "primarySong"});
    hymnCollection.insert({number: 281, numberText: "281", name: "The Wise Man and the Foolish Man", type: "primarySong"});
    hymnCollection.insert({number: 282, numberText: "282", name: "Feliz Cumpleaños", type: "primarySong"});
    hymnCollection.insert({number: 283, numberText: "283", name: "Your Happy Birthday", type: "primarySong"});
    hymnCollection.insert({number: 284, numberText: "284", name: "Have a Very Happy Birthday!", type: "primarySong"});
    hymnCollection.insert({number: 284, numberText: "284", name: "Happy, Happy Birthday", type: "primarySong"});
    hymnCollection.insert({number: 285, numberText: "285", name: "You've Had a Birthday (Round)", type: "primarySong"});
  };

  if (recognitionTypeCollection.find().count() === 0) {
    recognitionTypeCollection.insert({typeName: "Baby Blessing"});
    recognitionTypeCollection.insert({typeName: "Baptism"});
    recognitionTypeCollection.insert({typeName: "Confirmation"});
    recognitionTypeCollection.insert({typeName: "Advancement from Primary"});
    recognitionTypeCollection.insert({typeName: "Conferral of Aaronic Priesthood"});
    recognitionTypeCollection.insert({typeName: "Ordination to the Office of Deacon"});
    recognitionTypeCollection.insert({typeName: "Ordination to the Office of Teacher"});
    recognitionTypeCollection.insert({typeName: "Ordination to the Office of Priest"});
    recognitionTypeCollection.insert({typeName: "Conferral of Melchizedek Priesthood"});
    recognitionTypeCollection.insert({typeName: "Ordination to the Office of Elder"});
    recognitionTypeCollection.insert({typeName: "Ordination to the Office of High Priest"});
    recognitionTypeCollection.insert({typeName: "Eagle Scout Award"});
    recognitionTypeCollection.insert({typeName: "Duty to God Award"});
    recognitionTypeCollection.insert({typeName: "Personal Progress"});
    recognitionTypeCollection.insert({typeName: "Young Womanhood Recognition"});
    recognitionTypeCollection.insert({typeName: "Seminary Attendance Certificate"});
    recognitionTypeCollection.insert({typeName: "Seminary Completion Certificate"});
    recognitionTypeCollection.insert({typeName: "Seminary Graduation"});
    recognitionTypeCollection.insert({typeName: "Mission Call"});
    recognitionTypeCollection.insert({typeName: "Wedding"});
    recognitionTypeCollection.insert({typeName: "Temple Sealing"});
    recognitionTypeCollection.insert({typeName: "Funeral"});
  }

  if (callingCollection.find({wardUnitNo: -1}).count() === 0) {
    //dump in generic callings too
    //callingCollection.insert({positionName: "Bishopric", wardUnitNo: -1});
    callingCollection.insert({positionName: "Bishop", wardUnitNo: -1});
    callingCollection.insert({positionName: "Bishopric First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Bishopric Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Ward Executive Secretary", wardUnitNo: -1});
    callingCollection.insert({positionName: "Ward Clerk", wardUnitNo: -1});
    callingCollection.insert({positionName: "Ward Assistant Clerk", wardUnitNo: -1});
    callingCollection.insert({positionName: "Ward Assistant Clerk--Membership", wardUnitNo: -1});
    callingCollection.insert({positionName: "Ward Assistant Clerk—Finance", wardUnitNo: -1});
    callingCollection.insert({positionName: "(Acting Ward Leader)", wardUnitNo: -1});
    //callingCollection.insert({positionName: "High Priests Group Leadership", wardUnitNo: -1});
    callingCollection.insert({positionName: "High Priests Group Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "High Priests Group First Assistant", wardUnitNo: -1});
    callingCollection.insert({positionName: "High Priests Group Second Assistant", wardUnitNo: -1});
    callingCollection.insert({positionName: "High Priests Group Secretary", wardUnitNo: -1});
    callingCollection.insert({positionName: "High Priests Group Assistant Secretary", wardUnitNo: -1});
    callingCollection.insert({positionName: "High Priests Group", wardUnitNo: -1});
    callingCollection.insert({positionName: "High Priests Group Instructor", wardUnitNo: -1});
    callingCollection.insert({positionName: "High Priests Home Teaching District Supervisor", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Elders Quorum Presidency", wardUnitNo: -1});
    callingCollection.insert({positionName: "Elders Quorum President", wardUnitNo: -1});
    callingCollection.insert({positionName: "Elders Quorum First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Elders Quorum Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Elders Quorum Secretary", wardUnitNo: -1});
    callingCollection.insert({positionName: "Elders Quorum Assistant Secretary", wardUnitNo: -1});
    callingCollection.insert({positionName: "Elders Quorum", wardUnitNo: -1});
    callingCollection.insert({positionName: "Elders Quorum Instructor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Elders Home Teaching District Supervisor", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Relief Society Presidency", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society President", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Secretary", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Assistant Secretary", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Meeting Coordinator", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Meeting Committee Member", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Compassionate", wardUnitNo: -1});
    callingCollection.insert({positionName: "Service Coordinator", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Compassionate", wardUnitNo: -1});
    callingCollection.insert({positionName: "Service Assistant Coordinator", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Teacher", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Visiting Teaching Coordinator", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Visiting Teaching", wardUnitNo: -1});
    callingCollection.insert({positionName: "District Supervisor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Music Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Pianist", wardUnitNo: -1});
    callingCollection.insert({positionName: "Relief Society Adviser to Young", wardUnitNo: -1});
    callingCollection.insert({positionName: "Single Adult Sisters", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Single Adult", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Single Adult Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Single Adult Leader", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Young Men Presidency", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Men President", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Men First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Men Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Men Secretary", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Priests Quorum", wardUnitNo: -1});
    callingCollection.insert({positionName: "Priests Quorum First Assistant", wardUnitNo: -1});
    callingCollection.insert({positionName: "Priests Quorum Second Assistant", wardUnitNo: -1});
    callingCollection.insert({positionName: "Priests Quorum Secretary", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Teachers Quorum", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teachers Quorum President", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teachers Quorum First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teachers Quorum Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teachers Quorum Secretary", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Deacons Quorum", wardUnitNo: -1});
    callingCollection.insert({positionName: "Deacons Quorum President", wardUnitNo: -1});
    callingCollection.insert({positionName: "Deacons Quorum First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Deacons Quorum Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Deacons Quorum Secretary", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Scouting", wardUnitNo: -1});
    callingCollection.insert({positionName: "Scouting Committee Chairman", wardUnitNo: -1});
    callingCollection.insert({positionName: "Scouting Committee Member", wardUnitNo: -1});
    callingCollection.insert({positionName: "Scoutmaster", wardUnitNo: -1});
    callingCollection.insert({positionName: "Assistant Scoutmaster", wardUnitNo: -1});
    callingCollection.insert({positionName: "Varsity Coach", wardUnitNo: -1});
    callingCollection.insert({positionName: "Assistant Varsity Coach", wardUnitNo: -1});
    callingCollection.insert({positionName: "Venturing Crew Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Assistant Venturing Crew Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Executive Officer", wardUnitNo: -1});
    callingCollection.insert({positionName: "Chartered Organization Representative", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Young Men", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Men Stake Youth", wardUnitNo: -1});
    callingCollection.insert({positionName: "Committee Member", wardUnitNo: -1});
    callingCollection.insert({positionName: "Priests Quorum Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Priests Quorum Assistant Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teachers Quorum Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teachers Quorum Assistant Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Deacons Quorum Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Deacons Quorum Assistant Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Men Sports Coach", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women Presidency", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women President", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women Secretary", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Laurel", wardUnitNo: -1});
    callingCollection.insert({positionName: "Laurel President", wardUnitNo: -1});
    callingCollection.insert({positionName: "Laurel First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Laurel Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Laurel Secretary", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Mia Maid", wardUnitNo: -1});
    callingCollection.insert({positionName: "Mia Maid President", wardUnitNo: -1});
    callingCollection.insert({positionName: "Mia Maid First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Mia Maid Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Mia Maid Secretary", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Beehive", wardUnitNo: -1});
    callingCollection.insert({positionName: "Beehive President", wardUnitNo: -1});
    callingCollection.insert({positionName: "Beehive First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Beehive Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Beehive Secretary", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Young Women", wardUnitNo: -1});
    callingCollection.insert({positionName: "Laurel Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Laurel Assistant Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Mia Maid Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Mia Maid Assistant Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Beehive Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Beehive Assistant Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women Music Director", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women Pianist", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women Activity Specialist", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women Camp Director", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women Assistant Camp Director", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women Stake Youth Committee", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women Sports Specialist", wardUnitNo: -1});
    callingCollection.insert({positionName: "Young Women Assistant Sports", wardUnitNo: -1});
    callingCollection.insert({positionName: "Specialist", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School Presidency", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School President", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School Secretary", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Sunday School", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School Teacher", wardUnitNo: -1});
    callingCollection.insert({positionName: "Meetinghouse Librarian", wardUnitNo: -1});
    callingCollection.insert({positionName: "Librarian", wardUnitNo: -1});
    callingCollection.insert({positionName: "Assistant Librarian", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teacher - Gospel Doctrine", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teacher - Gospel Principles", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teacher - Marriage and Family Relations", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teacher - Missionary Preparation", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teacher - Teaching the Gospel", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teacher - Temple Preparation", wardUnitNo: -1});
    callingCollection.insert({positionName: "Teacher - Temple and Family", wardUnitNo: -1});
    //callingCollection.insert({positionName: "History", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School Teacher - Course 12", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School Teacher - Course 13", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School Teacher - Course 14", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School Teacher - Course 15", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School Teacher - Course 16", wardUnitNo: -1});
    callingCollection.insert({positionName: "Sunday School Teacher - Course 17", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Primary Presidency", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary President", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary First Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Second Counselor", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Secretary", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Primary", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Teacher", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Pianist", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Music Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Nursery Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Nursery Leader - Pre-Nursery", wardUnitNo: -1});
    callingCollection.insert({positionName: "Nursery Music Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Teacher - Sunbeam", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Teacher - CTR 4", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Teacher - CTR 5", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Teacher - CTR 6", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Teacher - CTR 7", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Teacher - Valiant 8", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Teacher - Valiant 9", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Teacher - Valiant 10", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Teacher - Valiant 11", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Cub Scouts", wardUnitNo: -1});
    callingCollection.insert({positionName: "Cub Scout Committee Chairman", wardUnitNo: -1});
    callingCollection.insert({positionName: "Cub Scout Committee Member", wardUnitNo: -1});
    callingCollection.insert({positionName: "Cubmaster", wardUnitNo: -1});
    callingCollection.insert({positionName: "Webelos Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Webelos Assistant Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Bear Den Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Bear Den Assistant Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Wolf Den Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Wolf Den Assistant Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Scouting (eleven year old)", wardUnitNo: -1});
    callingCollection.insert({positionName: "Eleven-Year-Old Scout Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Activity Days", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Activity Days Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Primary Activity Days Assistant Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Technology", wardUnitNo: -1});
    callingCollection.insert({positionName: "Website Administrator", wardUnitNo: -1});
    callingCollection.insert({positionName: "Activities and Sports", wardUnitNo: -1});
    callingCollection.insert({positionName: "Athletic Director", wardUnitNo: -1});
    callingCollection.insert({positionName: "Activities Committee Chairman", wardUnitNo: -1});
    callingCollection.insert({positionName: "Activities Committee Specialist", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Ward Missionaries", wardUnitNo: -1});
    callingCollection.insert({positionName: "Mission Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Missionary - Ward", wardUnitNo: -1});
    callingCollection.insert({positionName: "Missionary - Full Time", wardUnitNo: -1});
    callingCollection.insert({positionName: "Employment and Welfare", wardUnitNo: -1});
    callingCollection.insert({positionName: "Welfare Specialist", wardUnitNo: -1});
    callingCollection.insert({positionName: "Employment Specialist", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Music", wardUnitNo: -1});
    callingCollection.insert({positionName: "Priesthood Pianist or Organist", wardUnitNo: -1});
    callingCollection.insert({positionName: "Priesthood Music Director", wardUnitNo: -1});
    callingCollection.insert({positionName: "Choir Accompanist", wardUnitNo: -1});
    callingCollection.insert({positionName: "Music Adviser", wardUnitNo: -1});
    callingCollection.insert({positionName: "Choir Director", wardUnitNo: -1});
    callingCollection.insert({positionName: "Chorister", wardUnitNo: -1});
    callingCollection.insert({positionName: "Organist or Pianist", wardUnitNo: -1});
    callingCollection.insert({positionName: "Music Director", wardUnitNo: -1});
    callingCollection.insert({positionName: "Music Chairman", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Facilities", wardUnitNo: -1});
    callingCollection.insert({positionName: "Building Representative", wardUnitNo: -1});
    callingCollection.insert({positionName: "Scheduler--Building 1", wardUnitNo: -1});
    callingCollection.insert({positionName: "Scheduler--Building 2", wardUnitNo: -1});
    callingCollection.insert({positionName: "Scheduler--Building 3", wardUnitNo: -1});
    callingCollection.insert({positionName: "Scheduler--Building 4", wardUnitNo: -1});
    callingCollection.insert({positionName: "Scheduler--Building 5", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Family History", wardUnitNo: -1});
    callingCollection.insert({positionName: "Family History Leader", wardUnitNo: -1});
    callingCollection.insert({positionName: "Family History Consultant", wardUnitNo: -1});
    callingCollection.insert({positionName: "Indexing Director", wardUnitNo: -1});
    callingCollection.insert({positionName: "Indexing Assistant Director", wardUnitNo: -1});
    callingCollection.insert({positionName: "Indexing Worker", wardUnitNo: -1});
    //callingCollection.insert({positionName: "Other Callings", wardUnitNo: -1});
    callingCollection.insert({positionName: "History Specialist", wardUnitNo: -1});
    callingCollection.insert({positionName: "Magazine Representative", wardUnitNo: -1});
    callingCollection.insert({positionName: "Ward Disability Specialist", wardUnitNo: -1});
  }

  if (organizationCollection.find().count() === 0) {
    organizationCollection.insert({key: "HIGH_PRIEST", name: "High Priests", order: 1});
    organizationCollection.insert({key: "ELDER", name: "Elders", order: 2});
    organizationCollection.insert({key: "RELIEF_SOCIETY", name: "Relief Society", order: 3});
    organizationCollection.insert({key: "PRIEST", name: "Priests", order: 4});
    organizationCollection.insert({key: "TEACHER", name: "Teachers", order: 5});
    organizationCollection.insert({key: "DEACON", name: "Deacons", order: 6});
    organizationCollection.insert({key: "LAUREL", name: "Laurels", order: 7});
    organizationCollection.insert({key: "MIA_MAID", name: "Mia Maids", order: 8});
    organizationCollection.insert({key: "BEEHIVE", name: "Beehives", order: 9});
    organizationCollection.insert({key: "ADULTS", name: "Adults", order: 10});
  }
});
